export const contingencyReasons = ["BIOMETRIC_NO_MATCH", "BIOMETRIC_PROVIDER_UNAVAILABLE", "BIOMETRIC_ATTEMPTS_EXCEEDED", "LIVENESS_FAILED", "PHOTO_ATTACK_SUSPECTED", "VIDEO_ATTACK_SUSPECTED", "CAMERA_UNAVAILABLE", "LOCATION_UNAVAILABLE", "LOCATION_LOW_ACCURACY", "LOCATION_PERMISSION_DENIED", "OUTSIDE_GEOFENCE", "GEOFENCE_SERVICE_ERROR", "NETWORK_OFFLINE", "BACKEND_UNAVAILABLE", "OFFLINE_LIMIT_EXCEEDED", "COLLECTOR_ERROR", "COLLECTOR_UNAUTHORIZED", "COLLECTOR_CREDENTIAL_SUSPECTED_CLONE", "CLOCK_DRIFT_HIGH", "DEVICE_TIME_CHANGED", "TIME_ROLLBACK_DETECTED", "DEVICE_TIMEZONE_MISMATCH", "POTENTIAL_DUPLICATE", "UNKNOWN_TECHNICAL_ERROR"] as const;
export type ContingencyReason = typeof contingencyReasons[number];
export type ContingencyCategory = "TECHNICAL_FAILURE" | "VALIDATION_REJECTED" | "SECURITY_REJECTION";
export type ContingencyResolution = "RETRY" | "SUPERVISED" | "OFFLINE_QUEUE" | "REJECT" | "BLOCK";
export type ContingencyAuthorization = "ADMIN" | "AUTHORIZED_MANAGER" | "SIGNED_OFFLINE_TICKET";
export type ContingencyEventStatus = "OPEN" | "AUTHORIZED" | "REGISTERED" | "REJECTED" | "REQUIRES_REVIEW" | "RESOLVED" | "CANCELLED";
export type ContingencyPolicyDecision = { reason: ContingencyReason; category: ContingencyCategory; resolution: ContingencyResolution; allowsContingency: boolean; requiresSupervisor: boolean };
