import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { contingencyRequests, employees, establishments, repCollectors, repRegistrars } from "@/db/schema";
import { decideContingency } from "@/modules/attendance-contingency/policies/contingency-policy.service";
import { contingencyReasons } from "@/modules/attendance-contingency/types";
import { recordRepPEvent } from "@/rep-p/audit.service";
import { consumeRateLimit } from "@/services/rate-limit.service";
import { authenticateTerminal } from "@/services/terminal-auth.service";
export const runtime = "nodejs";
const eligibleReasons = contingencyReasons.filter((reason) => decideContingency(reason).requiresSupervisor);
const schema = z.object({ registrationNumber: z.string().trim().min(1).max(50), eventType: z.enum(["CLOCK_IN", "CLOCK_OUT"]), failureType: z.enum(contingencyReasons), reason: z.string().trim().min(10).max(500) }).strict();
export async function POST(request: Request) { const collector = await authenticateTerminal(); if (!collector) return Response.json({ error: "COLLECTOR_UNAUTHORIZED" }, { status: 401 }); const limited = await consumeRateLimit(request, "contingency-request", 5, 300, collector.id); if (!limited.allowed) return Response.json({ error: "Muitas solicitações. Aguarde antes de tentar novamente." }, { status: 429 }); const input = schema.safeParse(await request.json().catch(() => null)); if (!input.success || !eligibleReasons.includes(input.data.failureType)) return Response.json({ error: "Motivo não elegível para contingência supervisionada." }, { status: 422 }); const policy = decideContingency(input.data.failureType); const [employee] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.registrationNumber, input.data.registrationNumber), eq(employees.status, "ACTIVE"), eq(employees.isActive, true))).limit(1); if (!employee) return Response.json({ error: "Funcionário ativo não localizado." }, { status: 404 }); const [context] = await db.select({ establishmentId: establishments.id }).from(repCollectors).innerJoin(repRegistrars, eq(repRegistrars.id, repCollectors.registrarId)).innerJoin(establishments, eq(establishments.id, repRegistrars.establishmentId)).where(eq(repCollectors.id, collector.id)).limit(1); if (!context) return Response.json({ error: "Terminal sem estabelecimento." }, { status: 422 }); const [saved] = await db.insert(contingencyRequests).values({ employeeId: employee.id, collectorId: collector.id, establishmentId: context.establishmentId, eventType: input.data.eventType, failureType: input.data.failureType, category: policy.category, originalFlowStatus: "FAILED", reason: input.data.reason, status: "PENDING" }).returning({ id: contingencyRequests.id, requestedAt: contingencyRequests.requestedAt }); await recordRepPEvent(db, { eventType: "CONTINGENCY_REQUESTED", outcome: "SUCCESS", collectorId: collector.id, employeeId: employee.id, reasonCode: input.data.failureType, metadata: { contingencyEventId: saved.id, category: policy.category } }); return Response.json(saved, { status: 201, headers: { "Cache-Control": "no-store" } }); }
