import { index, integer, jsonb, numeric, pgTable, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { employees } from "./employees";
import { establishments, repCollectors } from "./rep-p";
import { users } from "./users";

export const employeeBiometricProfiles = pgTable("employee_biometric_profiles", { id: uuid("id").defaultRandom().primaryKey(), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }), status: varchar("status", { length: 30 }).notNull().default("PENDING"), templateVersion: varchar("template_version", { length: 30 }).notNull(), algorithmVersion: varchar("algorithm_version", { length: 50 }).notNull(), provider: varchar("provider", { length: 50 }).notNull(), privacyNoticeVersion: varchar("privacy_notice_version", { length: 30 }).notNull(), policyVersion: varchar("policy_version", { length: 30 }).notNull(), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }), enrolledAt: timestamp("enrolled_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("employee_biometric_profiles_employee_unique").on(table.employeeId), index("employee_biometric_profiles_status_idx").on(table.status)]);

export const biometricTemplates = pgTable("biometric_templates", { id: uuid("id").defaultRandom().primaryKey(), biometricProfileId: uuid("biometric_profile_id").notNull().references(() => employeeBiometricProfiles.id, { onDelete: "restrict" }), encryptedTemplate: varchar("encrypted_template", { length: 16_000 }).notNull(), encryptionVersion: varchar("encryption_version", { length: 30 }).notNull(), provider: varchar("provider", { length: 50 }).notNull(), algorithmVersion: varchar("algorithm_version", { length: 50 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), revokedAt: timestamp("revoked_at", { withTimezone: true }) }, (table) => [index("biometric_templates_profile_idx").on(table.biometricProfileId, table.createdAt)]);

export const biometricValidations = pgTable("biometric_validations", { id: uuid("id").defaultRandom().primaryKey(), attemptId: uuid("attempt_id").notNull(), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "restrict" }), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "restrict" }), method: varchar("method", { length: 30 }).notNull(), provider: varchar("provider", { length: 50 }).notNull(), livenessStatus: varchar("liveness_status", { length: 30 }).notNull(), livenessScore: numeric("liveness_score", { precision: 8, scale: 6 }), matchStatus: varchar("match_status", { length: 30 }).notNull(), similarityScore: numeric("similarity_score", { precision: 8, scale: 6 }), riskFlags: jsonb("risk_flags").$type<string[]>().notNull().default([]), capturedAt: timestamp("captured_at", { withTimezone: true }).notNull(), validatedAt: timestamp("validated_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("biometric_validations_collector_time_idx").on(table.collectorId, table.createdAt), uniqueIndex("biometric_validations_attempt_unique").on(table.attemptId)]);

export const pointRegistrationAttempts = pgTable("point_registration_attempts", { id: uuid("id").defaultRandom().primaryKey(), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "restrict" }), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), locationValidationId: uuid("location_validation_id"), biometricValidationId: uuid("biometric_validation_id"), status: varchar("status", { length: 30 }).notNull().default("STARTED"), failureReason: varchar("failure_reason", { length: 100 }), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), metrics: jsonb("metrics").$type<Record<string, number>>().notNull().default({}) }, (table) => [index("point_registration_attempts_collector_time_idx").on(table.collectorId, table.startedAt)]);

export const contingencyRequests = pgTable("contingency_requests", { id: uuid("id").defaultRandom().primaryKey(), attemptId: uuid("attempt_id"), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "restrict" }), establishmentId: uuid("establishment_id").references(() => establishments.id, { onDelete: "restrict" }), eventType: varchar("event_type", { length: 20 }).notNull(), failureType: varchar("failure_type", { length: 50 }).notNull(), category: varchar("category", { length: 30 }).notNull().default("TECHNICAL_FAILURE"), originalFlowStatus: varchar("original_flow_status", { length: 40 }), authorizationMethod: varchar("authorization_method", { length: 40 }), reason: varchar("reason", { length: 500 }).notNull(), status: varchar("status", { length: 20 }).notNull().default("PENDING"), requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(), reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "restrict" }), reviewedAt: timestamp("reviewed_at", { withTimezone: true }), decisionReason: varchar("decision_reason", { length: 500 }), timeEntryId: uuid("time_entry_id"), resolvedAt: timestamp("resolved_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("contingency_requests_status_time_idx").on(table.status, table.requestedAt), index("contingency_requests_employee_time_idx").on(table.employeeId, table.requestedAt)]);

export const offlinePointOperations = pgTable("offline_point_operations", { id: uuid("id").defaultRandom().primaryKey(), operationId: varchar("operation_id", { length: 100 }).notNull(), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "restrict" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "restrict" }), contingencyEventId: uuid("contingency_event_id").references(() => contingencyRequests.id, { onDelete: "restrict" }), status: varchar("status", { length: 30 }).notNull().default("PENDING"), deviceCapturedAt: timestamp("device_captured_at", { withTimezone: true }).notNull(), receivedAtServer: timestamp("received_at_server", { withTimezone: true }).notNull().defaultNow(), lastServerTime: timestamp("last_server_time", { withTimezone: true }), lastClockSyncAt: timestamp("last_clock_sync_at", { withTimezone: true }), clockOffsetMs: integer("clock_offset_ms"), retryCount: integer("retry_count").notNull().default(0), riskFlags: jsonb("risk_flags").$type<string[]>().notNull().default([]), timeEntryId: uuid("time_entry_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), resolvedAt: timestamp("resolved_at", { withTimezone: true }) }, (table) => [uniqueIndex("offline_point_operations_operation_unique").on(table.operationId), index("offline_point_operations_status_time_idx").on(table.status, table.createdAt)]);

export const securityEvents = pgTable("security_events", { id: uuid("id").defaultRandom().primaryKey(), type: varchar("type", { length: 50 }).notNull(), severity: varchar("severity", { length: 20 }).notNull(), collectorId: uuid("collector_id").references(() => repCollectors.id, { onDelete: "restrict" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "restrict" }), attemptId: uuid("attempt_id"), metadataSafe: jsonb("metadata_safe").$type<Record<string, unknown>>().notNull().default({}), detectedAt: timestamp("detected_at", { withTimezone: true }).notNull().defaultNow(), resolvedAt: timestamp("resolved_at", { withTimezone: true }) }, (table) => [index("security_events_type_time_idx").on(table.type, table.detectedAt), index("security_events_collector_time_idx").on(table.collectorId, table.detectedAt)]);
