import { date, index, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { correctionRequestTypeEnum, requestStatusEnum } from "./enums";
import { employees } from "./employees";
import { users } from "./users";

export const managerEmployees = pgTable("manager_employees", { id: uuid("id").defaultRandom().primaryKey(), managerUserId: uuid("manager_user_id").notNull().references(() => users.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("manager_employees_unique").on(table.managerUserId, table.employeeId), index("manager_employees_manager_idx").on(table.managerUserId)]);

export const correctionRequests = pgTable("correction_requests", { id: uuid("id").defaultRandom().primaryKey(), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }), date: date("date", { mode: "string" }).notNull(), type: correctionRequestTypeEnum("type").notNull(), requestedTime: varchar("requested_time", { length: 5 }), reason: text("reason").notNull(), status: requestStatusEnum("status").notNull().default("PENDING"), requestedBy: uuid("requested_by").notNull().references(() => users.id, { onDelete: "restrict" }), reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "restrict" }), reviewReason: text("review_reason"), reviewedAt: timestamp("reviewed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("correction_requests_employee_idx").on(table.employeeId), index("correction_requests_status_idx").on(table.status)]);

export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), recipientUserId: uuid("recipient_user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 150 }).notNull(), message: text("message").notNull(), link: varchar("link", { length: 500 }), readAt: timestamp("read_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("notifications_recipient_idx").on(table.recipientUserId, table.createdAt)]);
