import { bigint, boolean, index, jsonb, numeric, pgTable, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { users } from "./users";
import { employees } from "./employees";
import { repCollectorStatusEnum, repModeEnum, repRegistrarStatusEnum } from "./enums";

export const establishments = pgTable("establishments", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 150 }).notNull(), cnpj: varchar("cnpj", { length: 14 }).notNull(), timezone: varchar("timezone", { length: 50 }).notNull().default("America/Belem"), isActive: boolean("is_active").notNull().default(true), latitude: numeric("latitude", { precision: 10, scale: 7 }), longitude: numeric("longitude", { precision: 10, scale: 7 }), geofenceRadiusMeters: numeric("geofence_radius_meters", { precision: 8, scale: 2 }), geofenceEnabled: boolean("geofence_enabled").notNull().default(false), minimumLocationAccuracyMeters: numeric("minimum_location_accuracy_meters", { precision: 8, scale: 2 }).notNull().default("30"), locationMaxAgeSeconds: bigint("location_max_age_seconds", { mode: "number" }).notNull().default(30), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("establishments_cnpj_unique").on(table.cnpj), index("establishments_active_idx").on(table.isActive)]);

export const repRegistrars = pgTable("rep_registrars", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), name: varchar("name", { length: 150 }).notNull(), mode: repModeEnum("mode").notNull(), status: repRegistrarStatusEnum("status").notNull().default("DRAFT"), identifier: varchar("identifier", { length: 100 }).notNull(), inpiRegistration: varchar("inpi_registration", { length: 17 }), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_registrars_identifier_unique").on(table.identifier), index("rep_registrars_establishment_idx").on(table.establishmentId)]);

export const repConfigurations = pgTable("rep_configurations", { id: uuid("id").defaultRandom().primaryKey(), registrarId: uuid("registrar_id").notNull().references(() => repRegistrars.id, { onDelete: "cascade" }), officialTimezone: varchar("official_timezone", { length: 50 }).notNull().default("America/Belem"), registrationEnabled: boolean("registration_enabled").notNull().default(false), settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_configurations_registrar_unique").on(table.registrarId)]);

export const repCollectors = pgTable("rep_collectors", { id: uuid("id").defaultRandom().primaryKey(), registrarId: uuid("registrar_id").notNull().references(() => repRegistrars.id, { onDelete: "restrict" }), name: varchar("name", { length: 150 }).notNull(), deviceIdentifier: varchar("device_identifier", { length: 150 }).notNull(), status: repCollectorStatusEnum("status").notNull().default("INACTIVE"), credentialHash: varchar("credential_hash", { length: 64 }).notNull(), credentialPrefix: varchar("credential_prefix", { length: 12 }).notNull(), terminalVersion: varchar("terminal_version", { length: 30 }), activeInstanceId: varchar("active_instance_id", { length: 100 }), activeInstanceSeenAt: timestamp("active_instance_seen_at", { withTimezone: true }), pendingOperationCount: bigint("pending_operation_count", { mode: "number" }).notNull().default(0), offlineSince: timestamp("offline_since", { withTimezone: true }), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), activatedAt: timestamp("activated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_collectors_device_unique").on(table.deviceIdentifier), uniqueIndex("rep_collectors_credential_unique").on(table.credentialHash), index("rep_collectors_registrar_idx").on(table.registrarId)]);

export const repCollectorActivations = pgTable("rep_collector_activations", { id: uuid("id").defaultRandom().primaryKey(), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "cascade" }), codeHash: varchar("code_hash", { length: 64 }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_collector_activations_code_unique").on(table.codeHash), index("rep_collector_activations_collector_idx").on(table.collectorId)]);

export const repNsrSequences = pgTable("rep_nsr_sequences", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), currentValue: bigint("current_value", { mode: "number" }).notNull().default(0), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_nsr_sequences_establishment_unique").on(table.establishmentId)]);

export const repPEvents = pgTable("rep_p_events", { id: uuid("id").defaultRandom().primaryKey(), eventType: varchar("event_type", { length: 50 }).notNull(), outcome: varchar("outcome", { length: 20 }).notNull(), registrarId: uuid("registrar_id").references(() => repRegistrars.id, { onDelete: "restrict" }), collectorId: uuid("collector_id").references(() => repCollectors.id, { onDelete: "restrict" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "restrict" }), nsr: varchar("nsr", { length: 30 }), reasonCode: varchar("reason_code", { length: 50 }), metadata: jsonb("metadata").$type<Record<string, unknown>>(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("rep_p_events_registrar_time_idx").on(table.registrarId, table.occurredAt), index("rep_p_events_collector_time_idx").on(table.collectorId, table.occurredAt)]);

export const locationValidations = pgTable("location_validations", { id: uuid("id").defaultRandom().primaryKey(), collectorId: uuid("collector_id").notNull().references(() => repCollectors.id, { onDelete: "restrict" }), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), latitude: numeric("latitude", { precision: 10, scale: 7 }), longitude: numeric("longitude", { precision: 10, scale: 7 }), accuracyMeters: numeric("accuracy_meters", { precision: 10, scale: 2 }), distanceMeters: numeric("distance_meters", { precision: 10, scale: 2 }), status: varchar("status", { length: 30 }).notNull(), capturedAt: timestamp("captured_at", { withTimezone: true }), validatedAt: timestamp("validated_at", { withTimezone: true }).notNull().defaultNow(), riskFlags: jsonb("risk_flags").$type<string[]>().notNull().default([]), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("location_validations_collector_time_idx").on(table.collectorId, table.createdAt), index("location_validations_establishment_time_idx").on(table.establishmentId, table.createdAt)]);

export const geofencePolicyChanges = pgTable("geofence_policy_changes", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), before: jsonb("before").$type<Record<string, unknown>>().notNull(), after: jsonb("after").$type<Record<string, unknown>>().notNull(), reason: varchar("reason", { length: 500 }).notNull(), changedBy: uuid("changed_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("geofence_policy_changes_establishment_idx").on(table.establishmentId, table.createdAt)]);
