import { bigint, boolean, index, jsonb, numeric, pgTable, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { users } from "./users";
import { employees } from "./employees";
import { repCollectorStatusEnum, repModeEnum, repRegistrarStatusEnum } from "./enums";

export const establishments = pgTable("establishments", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 150 }).notNull(), cnpj: varchar("cnpj", { length: 14 }).notNull(), timezone: varchar("timezone", { length: 50 }).notNull().default("America/Belem"), isActive: boolean("is_active").notNull().default(true), latitude: numeric("latitude", { precision: 10, scale: 7 }), longitude: numeric("longitude", { precision: 10, scale: 7 }), geofenceRadiusMeters: numeric("geofence_radius_meters", { precision: 8, scale: 2 }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("establishments_cnpj_unique").on(table.cnpj), index("establishments_active_idx").on(table.isActive)]);

export const repRegistrars = pgTable("rep_registrars", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), name: varchar("name", { length: 150 }).notNull(), mode: repModeEnum("mode").notNull(), status: repRegistrarStatusEnum("status").notNull().default("DRAFT"), identifier: varchar("identifier", { length: 100 }).notNull(), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_registrars_identifier_unique").on(table.identifier), index("rep_registrars_establishment_idx").on(table.establishmentId)]);

export const repConfigurations = pgTable("rep_configurations", { id: uuid("id").defaultRandom().primaryKey(), registrarId: uuid("registrar_id").notNull().references(() => repRegistrars.id, { onDelete: "cascade" }), officialTimezone: varchar("official_timezone", { length: 50 }).notNull().default("America/Belem"), registrationEnabled: boolean("registration_enabled").notNull().default(false), settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_configurations_registrar_unique").on(table.registrarId)]);

export const repCollectors = pgTable("rep_collectors", { id: uuid("id").defaultRandom().primaryKey(), registrarId: uuid("registrar_id").notNull().references(() => repRegistrars.id, { onDelete: "restrict" }), name: varchar("name", { length: 150 }).notNull(), deviceIdentifier: varchar("device_identifier", { length: 150 }).notNull(), status: repCollectorStatusEnum("status").notNull().default("INACTIVE"), credentialHash: varchar("credential_hash", { length: 64 }).notNull(), credentialPrefix: varchar("credential_prefix", { length: 12 }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), activatedAt: timestamp("activated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_collectors_device_unique").on(table.deviceIdentifier), uniqueIndex("rep_collectors_credential_unique").on(table.credentialHash), index("rep_collectors_registrar_idx").on(table.registrarId)]);

export const repNsrSequences = pgTable("rep_nsr_sequences", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), currentValue: bigint("current_value", { mode: "number" }).notNull().default(0), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_nsr_sequences_establishment_unique").on(table.establishmentId)]);

export const repPEvents = pgTable("rep_p_events", { id: uuid("id").defaultRandom().primaryKey(), eventType: varchar("event_type", { length: 50 }).notNull(), outcome: varchar("outcome", { length: 20 }).notNull(), registrarId: uuid("registrar_id").references(() => repRegistrars.id, { onDelete: "restrict" }), collectorId: uuid("collector_id").references(() => repCollectors.id, { onDelete: "restrict" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "restrict" }), nsr: varchar("nsr", { length: 30 }), reasonCode: varchar("reason_code", { length: 50 }), metadata: jsonb("metadata").$type<Record<string, unknown>>(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("rep_p_events_registrar_time_idx").on(table.registrarId, table.occurredAt), index("rep_p_events_collector_time_idx").on(table.collectorId, table.occurredAt)]);
