import { boolean, index, jsonb, pgTable, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { users } from "./users";
import { repModeEnum, repRegistrarStatusEnum } from "./enums";

export const establishments = pgTable("establishments", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 150 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });

export const repRegistrars = pgTable("rep_registrars", { id: uuid("id").defaultRandom().primaryKey(), establishmentId: uuid("establishment_id").notNull().references(() => establishments.id, { onDelete: "restrict" }), name: varchar("name", { length: 150 }).notNull(), mode: repModeEnum("mode").notNull(), status: repRegistrarStatusEnum("status").notNull().default("DRAFT"), identifier: varchar("identifier", { length: 100 }).notNull(), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_registrars_identifier_unique").on(table.identifier), index("rep_registrars_establishment_idx").on(table.establishmentId)]);

export const repConfigurations = pgTable("rep_configurations", { id: uuid("id").defaultRandom().primaryKey(), registrarId: uuid("registrar_id").notNull().references(() => repRegistrars.id, { onDelete: "cascade" }), officialTimezone: varchar("official_timezone", { length: 50 }).notNull().default("America/Belem"), registrationEnabled: boolean("registration_enabled").notNull().default(false), settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_configurations_registrar_unique").on(table.registrarId)]);
