import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { repSyncStatusEnum } from "./enums";
import { timeEntries } from "./time-entries";
import { users } from "./users";

export const repDevices = pgTable("rep_devices", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 150 }).notNull(), serialNumber: varchar("serial_number", { length: 100 }).notNull().unique(), manufacturer: varchar("manufacturer", { length: 100 }).notNull(), model: varchar("model", { length: 100 }).notNull(), adapter: varchar("adapter", { length: 50 }).notNull().default("MOCK"), credentialHash: varchar("credential_hash", { length: 64 }).notNull().unique(), credentialPrefix: varchar("credential_prefix", { length: 12 }).notNull(), isActive: boolean("is_active").notNull().default(true), lastSyncedNsr: varchar("last_synced_nsr", { length: 30 }), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("rep_devices_active_idx").on(table.isActive)]);

export const repSyncLogs = pgTable("rep_sync_logs", { id: uuid("id").defaultRandom().primaryKey(), repDeviceId: uuid("rep_device_id").notNull().references(() => repDevices.id, { onDelete: "restrict" }), requestId: varchar("request_id", { length: 100 }).notNull(), status: repSyncStatusEnum("status").notNull().default("RECEIVED"), receivedCount: integer("received_count").notNull().default(0), insertedCount: integer("inserted_count").notNull().default(0), duplicateCount: integer("duplicate_count").notNull().default(0), rejectedCount: integer("rejected_count").notNull().default(0), errorSummary: jsonb("error_summary").$type<Array<{ code: string; nsr?: string }>>(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => [uniqueIndex("rep_sync_logs_device_request_unique").on(table.repDeviceId, table.requestId), index("rep_sync_logs_device_created_idx").on(table.repDeviceId, table.createdAt)]);

export const repTimeRecords = pgTable("rep_time_records", { id: uuid("id").defaultRandom().primaryKey(), repDeviceId: uuid("rep_device_id").notNull().references(() => repDevices.id, { onDelete: "restrict" }), nsr: varchar("nsr", { length: 30 }).notNull(), timeEntryId: uuid("time_entry_id").notNull().unique().references(() => timeEntries.id, { onDelete: "restrict" }), rawFingerprint: varchar("raw_fingerprint", { length: 64 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_time_records_device_nsr_unique").on(table.repDeviceId, table.nsr), index("rep_time_records_device_idx").on(table.repDeviceId)]);

export const repAlertStates = pgTable("rep_alert_states", { id: uuid("id").defaultRandom().primaryKey(), repDeviceId: uuid("rep_device_id").notNull().references(() => repDevices.id, { onDelete: "cascade" }), type: varchar("type", { length: 30 }).notNull(), isActive: boolean("is_active").notNull().default(false), occurrenceCount: integer("occurrence_count").notNull().default(0), details: jsonb("details").$type<Record<string, unknown>>(), firstDetectedAt: timestamp("first_detected_at", { withTimezone: true }), lastDetectedAt: timestamp("last_detected_at", { withTimezone: true }), resolvedAt: timestamp("resolved_at", { withTimezone: true }), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("rep_alert_states_device_type_unique").on(table.repDeviceId, table.type), index("rep_alert_states_active_idx").on(table.isActive)]);

export const repReconciliationRuns = pgTable("rep_reconciliation_runs", { id: uuid("id").defaultRandom().primaryKey(), repDeviceId: uuid("rep_device_id").notNull().references(() => repDevices.id, { onDelete: "restrict" }), sourceName: varchar("source_name", { length: 100 }).notNull(), sourceCount: integer("source_count").notNull(), matchedCount: integer("matched_count").notNull(), missingCount: integer("missing_count").notNull(), alteredCount: integer("altered_count").notNull(), extraCount: integer("extra_count").notNull(), missingNsrs: jsonb("missing_nsrs").$type<string[]>().notNull(), alteredNsrs: jsonb("altered_nsrs").$type<string[]>().notNull(), extraNsrs: jsonb("extra_nsrs").$type<string[]>().notNull(), notes: text("notes"), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("rep_reconciliation_device_created_idx").on(table.repDeviceId, table.createdAt)]);
