import { and, eq, gte } from "drizzle-orm";
import { db } from "@/db";
import { notifications, repAlertStates, repDevices, repReconciliationRuns, repSyncLogs, repTimeRecords, users } from "@/db/schema";
import type { REPRecord } from "@/rep/contracts";
import { reconcileREPRecords } from "@/rep/reconciliation-core";

async function notifyAdmins(title: string, message: string) { const admins = await db.select({ id: users.id }).from(users).where(and(eq(users.role, "ADMIN"), eq(users.isActive, true))); if (admins.length) await db.insert(notifications).values(admins.map(({ id }) => ({ recipientUserId: id, title, message, link: "/admin/marcacoes" }))); }
async function setAlert(deviceId: string, type: string, active: boolean, details: Record<string, unknown>, message: string) { const [current] = await db.select().from(repAlertStates).where(and(eq(repAlertStates.repDeviceId, deviceId), eq(repAlertStates.type, type))).limit(1); const now = new Date(); if (!current) { await db.insert(repAlertStates).values({ repDeviceId: deviceId, type, isActive: active, occurrenceCount: active ? 1 : 0, details, firstDetectedAt: active ? now : undefined, lastDetectedAt: active ? now : undefined }); if (active) await notifyAdmins("Alerta de sincronização REP", message); return; } await db.update(repAlertStates).set({ isActive: active, details, occurrenceCount: active ? current.occurrenceCount + 1 : current.occurrenceCount, firstDetectedAt: active && !current.isActive ? now : current.firstDetectedAt, lastDetectedAt: active ? now : current.lastDetectedAt, resolvedAt: !active && current.isActive ? now : current.resolvedAt, updatedAt: now }).where(eq(repAlertStates.id, current.id)); if (active && !current.isActive) await notifyAdmins("Alerta de sincronização REP", message); }

export async function monitorREPDevices(stalledMinutes = 30) { const devices = await db.select().from(repDevices).where(eq(repDevices.isActive, true)); const failedSince = new Date(Date.now() - stalledMinutes * 60_000); for (const device of devices) { const stalled = !device.lastSeenAt || device.lastSeenAt < failedSince; await setAlert(device.id, "SYNC_STOPPED", stalled, { thresholdMinutes: stalledMinutes }, `${device.name} está sem sincronizar há mais de ${stalledMinutes} minutos.`); const [failure] = await db.select({ id: repSyncLogs.id }).from(repSyncLogs).where(and(eq(repSyncLogs.repDeviceId, device.id), eq(repSyncLogs.status, "FAILED"), gte(repSyncLogs.createdAt, failedSince))).limit(1); await setAlert(device.id, "DEVICE_FAILURE", Boolean(failure), { windowMinutes: stalledMinutes }, `${device.name} apresentou falha de sincronização.`); } return devices.length; }

export async function reconcileREPDevice(deviceId: string, sourceName: string, source: REPRecord[], createdBy: string, notes?: string) { const allImported = source.length ? await db.select({ nsr: repTimeRecords.nsr, fingerprint: repTimeRecords.rawFingerprint }).from(repTimeRecords).where(eq(repTimeRecords.repDeviceId, deviceId)) : []; const numericNsrs = source.map((record) => BigInt(record.nsr)); const minimum = numericNsrs.length ? numericNsrs.reduce((a, b) => a < b ? a : b) : BigInt(0); const maximum = numericNsrs.length ? numericNsrs.reduce((a, b) => a > b ? a : b) : BigInt(-1); const imported = allImported.filter(({ nsr }) => BigInt(nsr) >= minimum && BigInt(nsr) <= maximum); const result = reconcileREPRecords(source, imported); await db.insert(repReconciliationRuns).values({ repDeviceId: deviceId, sourceName, sourceCount: result.sourceCount, matchedCount: result.matchedCount, missingCount: result.missingNsrs.length, alteredCount: result.alteredNsrs.length, extraCount: result.extraNsrs.length, missingNsrs: result.missingNsrs, alteredNsrs: result.alteredNsrs, extraNsrs: result.extraNsrs, notes, createdBy }); await setAlert(deviceId, "NSR_GAP", result.missingNsrs.length > 0, { missingCount: result.missingNsrs.length }, `A conciliação encontrou ${result.missingNsrs.length} NSR(s) ausente(s).`); return result; }
