import "server-only";
import { and, eq, gt, isNull } from "drizzle-orm";
import { db } from "@/db";
import { repCollectorActivations, repCollectors } from "@/db/schema";
import { generateRepCredential, hashRepCredential } from "@/rep/credential";
import { ACTIVATION_TTL_MS, generateActivationCode, hashActivationCode } from "@/rep-p/activation-core";
import { recordRepPEvent } from "@/rep-p/audit.service";

function pepper() { const value = process.env.REP_CREDENTIAL_PEPPER; if (!value || value.length < 32) throw new Error("REP_CREDENTIAL_PEPPER não configurado com segurança."); return value; }
export async function issueCollectorActivation(collectorId: string, createdBy: string) { const code = generateActivationCode(); const now = new Date(); await db.transaction(async (tx) => { await tx.update(repCollectorActivations).set({ usedAt: now }).where(and(eq(repCollectorActivations.collectorId, collectorId), isNull(repCollectorActivations.usedAt))); await tx.insert(repCollectorActivations).values({ collectorId, codeHash: hashActivationCode(code, pepper()), expiresAt: new Date(now.getTime() + ACTIVATION_TTL_MS), createdBy }); }); return { code, expiresAt: new Date(now.getTime() + ACTIVATION_TTL_MS) }; }
export async function activateCollector(code: string) { const codeHash = hashActivationCode(code, pepper()); const now = new Date(); return db.transaction(async (tx) => { const [activation] = await tx.select({ id: repCollectorActivations.id, collectorId: repCollectorActivations.collectorId }).from(repCollectorActivations).where(and(eq(repCollectorActivations.codeHash, codeHash), isNull(repCollectorActivations.usedAt), gt(repCollectorActivations.expiresAt, now))).limit(1).for("update"); if (!activation) return undefined; const credential = generateRepCredential(); const [collector] = await tx.update(repCollectors).set({ status: "ACTIVE", credentialHash: hashRepCredential(credential.token, pepper()), credentialPrefix: credential.prefix, activatedAt: now, updatedAt: now }).where(eq(repCollectors.id, activation.collectorId)).returning({ id: repCollectors.id, name: repCollectors.name, registrarId: repCollectors.registrarId }); await tx.update(repCollectorActivations).set({ usedAt: now }).where(eq(repCollectorActivations.id, activation.id)); if (collector) await recordRepPEvent(tx, { eventType: "COLLECTOR_ACTIVATED", outcome: "SUCCESS", collectorId: collector.id, registrarId: collector.registrarId }); return collector ? { ...collector, token: credential.token } : undefined; }); }
