import "server-only";
import { and, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/db";
import { employees, repDevices, repSyncLogs, repTimeRecords, timeEntries } from "@/db/schema";
import type { REPBatch } from "@/rep/contracts";
import { verifyRepCredential } from "@/rep/credential";
import { deduplicateRepBatch, repExternalId, repRecordFingerprint } from "@/rep/rep-core";

function pepper() { const value = process.env.REP_CREDENTIAL_PEPPER; if (!value || value.startsWith("replace-with") || value.length < 32) throw new Error("REP_CREDENTIAL_PEPPER não configurado com segurança."); return value; }
export async function authenticateRepDevice(id: string, token: string) { const [device] = await db.select().from(repDevices).where(and(eq(repDevices.id, id), eq(repDevices.isActive, true))).limit(1); if (!device || !verifyRepCredential(token, device.credentialHash, pepper())) return undefined; return device; }
export async function processRepBatch(device: typeof repDevices.$inferSelect, requestId: string, batch: REPBatch) {
  const [existing] = await db.select().from(repSyncLogs).where(and(eq(repSyncLogs.repDeviceId, device.id), eq(repSyncLogs.requestId, requestId))).limit(1); if (existing) return { replay: true, syncId: existing.id, status: existing.status, received: existing.receivedCount, inserted: existing.insertedCount, duplicates: existing.duplicateCount, rejected: existing.rejectedCount, errors: existing.errorSummary ?? [] };
  const [created] = await db.insert(repSyncLogs).values({ repDeviceId: device.id, requestId, receivedCount: batch.records.length }).onConflictDoNothing().returning();
  if (!created) { const [concurrent] = await db.select().from(repSyncLogs).where(and(eq(repSyncLogs.repDeviceId, device.id), eq(repSyncLogs.requestId, requestId))).limit(1); if (!concurrent) throw new Error("Sincronização concorrente não localizada."); return { replay: true, syncId: concurrent.id, status: concurrent.status, received: concurrent.receivedCount, inserted: concurrent.insertedCount, duplicates: concurrent.duplicateCount, rejected: concurrent.rejectedCount, errors: concurrent.errorSummary ?? [] }; }
  try {
    const deduplicated = deduplicateRepBatch(batch.records); const registrations = [...new Set(deduplicated.unique.map((record) => record.employeeRegistration))]; const people = registrations.length ? await db.select({ id: employees.id, registrationNumber: employees.registrationNumber }).from(employees).where(inArray(employees.registrationNumber, registrations)) : []; const peopleByRegistration = new Map(people.map((employee) => [employee.registrationNumber, employee.id])); const errors: Array<{ code: string; nsr?: string }> = deduplicated.conflictingNsrs.map((nsr) => ({ code: "CONFLICTING_NSR_IN_BATCH", nsr })); let insertedCount = 0; let duplicateCount = deduplicated.duplicateNsrs.length; let rejectedCount = deduplicated.conflictingRecordCount; const acceptedNsrs: string[] = [];
    await db.transaction(async (tx) => { for (const record of deduplicated.unique) { const employeeId = peopleByRegistration.get(record.employeeRegistration); if (!employeeId) { rejectedCount++; if (errors.length < 50) errors.push({ code: "EMPLOYEE_NOT_FOUND", nsr: record.nsr }); continue; } const occurredAt = new Date(record.occurredAt); const [entry] = await tx.insert(timeEntries).values({ employeeId, occurredAt, source: "REP_C", externalId: repExternalId(device.id, record.nsr), deviceIdentifier: device.serialNumber, metadata: { repDeviceId: device.id, nsr: record.nsr, adapter: device.adapter, source: batch.source } }).onConflictDoNothing({ target: [timeEntries.source, timeEntries.externalId] }).returning(); if (!entry) { duplicateCount++; acceptedNsrs.push(record.nsr); continue; } await tx.insert(repTimeRecords).values({ repDeviceId: device.id, nsr: record.nsr, timeEntryId: entry.id, rawFingerprint: repRecordFingerprint(record) }); insertedCount++; acceptedNsrs.push(record.nsr); } });
    const status = rejectedCount ? "PARTIAL" as const : "PROCESSED" as const; const lastNsr = acceptedNsrs.reduce<string | undefined>((highest, value) => highest === undefined || BigInt(value) > BigInt(highest) ? value : highest, undefined); await db.transaction(async (tx) => { await tx.update(repSyncLogs).set({ status, insertedCount, duplicateCount, rejectedCount, errorSummary: errors, completedAt: new Date() }).where(eq(repSyncLogs.id, created.id)); await tx.update(repDevices).set({ lastSeenAt: new Date(), ...(lastNsr ? { lastSyncedNsr: sql<string>`case when ${repDevices.lastSyncedNsr} is null or cast(${repDevices.lastSyncedNsr} as numeric) < cast(${lastNsr} as numeric) then ${lastNsr} else ${repDevices.lastSyncedNsr} end` } : {}), updatedAt: new Date() }).where(eq(repDevices.id, device.id)); }); return { replay: false, syncId: created.id, status, received: batch.records.length, inserted: insertedCount, duplicates: duplicateCount, rejected: rejectedCount, errors };
  } catch (error) { await db.update(repSyncLogs).set({ status: "FAILED", errorSummary: [{ code: "INTERNAL_PROCESSING_ERROR" }], completedAt: new Date() }).where(eq(repSyncLogs.id, created.id)); throw error; }
}
