"use server";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/auth/session";
import { AccessConflictError, assignManagerEmployee, createPortalAccess } from "@/services/access.service";
import { log } from "@/services/logger";
import { managerScopeSchema, portalUserSchema } from "@/validations/access";

export async function createPortalAccessAction(formData: FormData) { const session = await requireAdmin(); const parsed = portalUserSchema.safeParse({ name: formData.get("name"), email: formData.get("email"), password: formData.get("password"), role: formData.get("role"), employeeId: formData.get("employeeId") || undefined }); if (!parsed.success) { const fields = new Set(parsed.error.issues.map((issue) => String(issue.path[0]))); const error = fields.has("password") ? "password" : fields.has("employeeId") ? "employee" : fields.has("email") ? "email" : fields.has("name") ? "name" : "invalid"; redirect(`/admin/acessos?error=${error}`); } try { await createPortalAccess(parsed.data, session.user.id); } catch (error) { if (error instanceof AccessConflictError) redirect(`/admin/acessos?error=${error.kind === "EMAIL" ? "email-exists" : "employee-exists"}`); log("error", "portal_access.creation_failed", { performedBy: session.user.id, role: parsed.data.role, error }); redirect("/admin/acessos?error=unexpected"); } redirect("/admin/acessos?saved=user"); }
export async function assignManagerEmployeeAction(formData: FormData) { const session = await requireAdmin(); const parsed = managerScopeSchema.safeParse({ managerUserId: formData.get("managerUserId"), employeeId: formData.get("employeeId") }); if (!parsed.success) redirect("/admin/acessos?error=scope"); await assignManagerEmployee(parsed.data.managerUserId, parsed.data.employeeId, session.user.id); redirect("/admin/acessos?saved=scope"); }
