"use server";
import { redirect } from "next/navigation";
import { enrollEmployeeBiometric, revokeEmployeeBiometric } from "@/modules/biometrics/services/biometric.service";
import { requireBiometricPermission } from "@/modules/biometrics/services/biometric-permission.service";
import { BIOMETRIC_POLICY_VERSION, PRIVACY_NOTICE_VERSION } from "@/modules/biometrics/privacy-notice";
import { db } from "@/db";
import { recordAudit } from "@/services/audit.service";
export async function enrollBiometricAction(employeeId: string, formData: FormData) { const session = await requireBiometricPermission("BIOMETRIC_ENROLL"); const image = String(formData.get("image") ?? ""); if (!image.startsWith("data:image/jpeg;base64,") || image.length > 3_500_000 || formData.get("acknowledged") !== "on") redirect(`/admin/funcionarios/${employeeId}/biometria?error=invalid`); try { const { profile, reenrollment } = await enrollEmployeeBiometric({ employeeId, image: Buffer.from(image.split(",")[1], "base64"), performedBy: session.user.id, privacyNoticeVersion: PRIVACY_NOTICE_VERSION, policyVersion: BIOMETRIC_POLICY_VERSION }); await recordAudit(db, { action: reenrollment ? "BIOMETRIC_REENROLLED" : "BIOMETRIC_ENROLLED", entity: "EMPLOYEE_BIOMETRIC_PROFILE", entityId: profile.id, performedBy: session.user.id, after: { employeeId, status: profile.status, provider: profile.provider, algorithmVersion: profile.algorithmVersion, privacyNoticeVersion: profile.privacyNoticeVersion } }); } catch { redirect(`/admin/funcionarios/${employeeId}/biometria?error=capture`); } redirect(`/admin/funcionarios/${employeeId}/biometria?saved=1`); }
export async function revokeBiometricAction(employeeId: string) { const session = await requireBiometricPermission("BIOMETRIC_REVOKE"); const profile = await revokeEmployeeBiometric(employeeId); if (profile) await recordAudit(db, { action: "BIOMETRIC_REVOKED", entity: "EMPLOYEE_BIOMETRIC_PROFILE", entityId: profile.id, performedBy: session.user.id, before: { employeeId, status: "ACTIVE" }, after: { employeeId, status: "REVOKED" }, reason: "Revogação administrativa" }); redirect(`/admin/funcionarios/${employeeId}/biometria?revoked=1`); }
