"use server";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/auth/session";
import { db } from "@/db";
import { contingencyRequests } from "@/db/schema";
import { recordRepPEvent } from "@/rep-p/audit.service";
import { registerRepPPoint } from "@/services/rep-p-registration.service";
export async function reviewContingencyAction(id: string, formData: FormData) { const session = await requireAdmin(); const decision = String(formData.get("decision")); const reason = String(formData.get("reason") ?? "").trim(); if (!id || !["APPROVED", "DENIED"].includes(decision) || reason.length < 10 || reason.length > 500) redirect("/admin/contingencias?error=review"); const [request] = await db.select().from(contingencyRequests).where(eq(contingencyRequests.id, id)).limit(1); if (!request || request.status !== "PENDING") redirect("/admin/contingencias?error=state"); if (session.user.employeeId === request.employeeId) redirect("/admin/contingencias?error=self-approval"); let timeEntryId: string | undefined; let nsr: string | undefined; if (decision === "APPROVED") { const result = await registerRepPPoint({ employeeId: request.employeeId, collectorId: request.collectorId, eventType: request.eventType as "CLOCK_IN" | "CLOCK_OUT", idempotencyKey: `contingency-${request.id}`, trustedOccurredAt: request.requestedAt, contingency: true, contingencyEventId: request.id, bypassWindowChecks: true }); timeEntryId = result.id; nsr = result.nsr; } const status = decision === "APPROVED" ? "REGISTERED" : "REJECTED"; await db.update(contingencyRequests).set({ status, authorizationMethod: decision === "APPROVED" ? "ADMIN" : null, reviewedBy: session.user.id, reviewedAt: new Date(), resolvedAt: new Date(), decisionReason: reason, timeEntryId }).where(eq(contingencyRequests.id, id)); await recordRepPEvent(db, { eventType: decision === "APPROVED" ? "CONTINGENCY_APPROVED" : "CONTINGENCY_DENIED", outcome: decision === "APPROVED" ? "SUCCESS" : "REJECTED", collectorId: request.collectorId, employeeId: request.employeeId, nsr, reasonCode: request.failureType, metadata: { contingencyEventId: request.id, authorizedBy: session.user.id, authorizationMethod: "ADMIN" } }); revalidatePath("/admin/contingencias"); }
