"use server";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/auth/session";
import { db } from "@/db";
import { establishments, geofencePolicyChanges } from "@/db/schema";
import { geofenceSettingsSchema } from "@/validations/geofence";
export async function updateGeofenceAction(formData: FormData) { const session = await requireAdmin(); const establishmentId = String(formData.get("establishmentId") ?? ""); const parsed = geofenceSettingsSchema.safeParse({ latitude: formData.get("latitude"), longitude: formData.get("longitude"), geofenceRadiusMeters: formData.get("geofenceRadiusMeters"), minimumLocationAccuracyMeters: formData.get("minimumLocationAccuracyMeters"), locationMaxAgeSeconds: formData.get("locationMaxAgeSeconds"), geofenceEnabled: formData.get("geofenceEnabled") === "on", reason: formData.get("reason") }); if (!parsed.success || !establishmentId) redirect("/admin/geofence?error=invalid"); await db.transaction(async (tx) => { const [before] = await tx.select().from(establishments).where(eq(establishments.id, establishmentId)).limit(1); if (!before) return; const values = { latitude: String(parsed.data.latitude), longitude: String(parsed.data.longitude), geofenceRadiusMeters: String(parsed.data.geofenceRadiusMeters), minimumLocationAccuracyMeters: String(parsed.data.minimumLocationAccuracyMeters), locationMaxAgeSeconds: parsed.data.locationMaxAgeSeconds, geofenceEnabled: parsed.data.geofenceEnabled, updatedAt: new Date() }; await tx.update(establishments).set(values).where(eq(establishments.id, establishmentId)); await tx.insert(geofencePolicyChanges).values({ establishmentId, before: { latitude: before.latitude, longitude: before.longitude, radius: before.geofenceRadiusMeters, accuracy: before.minimumLocationAccuracyMeters, enabled: before.geofenceEnabled }, after: values, reason: parsed.data.reason, changedBy: session.user.id }); }); revalidatePath("/admin/geofence"); redirect("/admin/geofence?saved=1"); }
