"use server";

import { redirect } from "next/navigation";
import { requireEmployeePortal, requireManagerPortal } from "@/auth/session";
import { confirmMedicalCertificate, prepareMedicalCertificateUpload, reviewMedicalCertificate } from "@/services/medical-certificate.service";
import { createCorrectionRequest, createPortalSwapRequest, managedEmployeeIds, markNotificationRead, notifyReviewers, notifyUser, reviewCorrectionRequest, reviewManagerSwap } from "@/services/portal.service";
import { medicalCertificateUploadSchema } from "@/validations/medical-certificate";
import { correctionRequestSchema, portalReviewSchema, portalSwapSchema } from "@/validations/portal";

export async function createPortalCorrectionAction(formData: FormData) { const session = await requireEmployeePortal(); const parsed = correctionRequestSchema.safeParse({ date: formData.get("date"), type: formData.get("type"), requestedTime: formData.get("requestedTime"), reason: formData.get("reason") }); if (!parsed.success) redirect("/portal/solicitacoes?error=correction"); await createCorrectionRequest(session.employeeId, session.user.id, parsed.data); redirect("/portal/solicitacoes?saved=correction"); }
export async function createPortalSwapAction(formData: FormData) { const session = await requireEmployeePortal(); const parsed = portalSwapSchema.safeParse({ dayOffDate: formData.get("dayOffDate"), workDate: formData.get("workDate"), reason: formData.get("reason") }); if (!parsed.success) redirect("/portal/solicitacoes?error=swap"); await createPortalSwapRequest(session.employeeId, session.user.id, parsed.data); redirect("/portal/solicitacoes?saved=swap"); }
export async function reviewPortalCorrectionAction(id: string, formData: FormData) { const session = await requireManagerPortal(); const parsed = portalReviewSchema.safeParse({ decision: formData.get("decision"), reason: formData.get("reason") }); if (!parsed.success) redirect("/gestao/solicitacoes?error=review"); const saved = await reviewCorrectionRequest(id, session.user.id, parsed.data.decision, parsed.data.reason); if (!saved) redirect("/acesso-negado"); redirect("/gestao/solicitacoes?saved=1"); }
export async function reviewPortalSwapAction(id: string, formData: FormData) { const session = await requireManagerPortal(); const parsed = portalReviewSchema.safeParse({ decision: formData.get("decision"), reason: formData.get("reason") }); if (!parsed.success) redirect("/gestao/solicitacoes?error=review"); const saved = await reviewManagerSwap(id, session.user.id, parsed.data.decision, parsed.data.reason); if (!saved) redirect("/acesso-negado"); redirect("/gestao/solicitacoes?saved=swap"); }
export async function reviewPortalCertificateAction(id: string, formData: FormData) { const session = await requireManagerPortal(); const parsed = portalReviewSchema.safeParse({ decision: formData.get("decision"), reason: formData.get("reason") }); if (!parsed.success) redirect("/gestao/solicitacoes?error=review"); const scope = await managedEmployeeIds(session.user.id); const result = await reviewMedicalCertificate(id, parsed.data.decision, parsed.data.reason, session.user.id, scope); if (!result) redirect("/acesso-negado"); await notifyUser(result.requestedBy, parsed.data.decision === "APPROVED" ? "Atestado aprovado" : "Atestado rejeitado", parsed.data.reason); redirect("/gestao/solicitacoes?saved=certificate"); }
export async function readNotificationAction(id: string) { const session = await requireEmployeePortal(); await markNotificationRead(id, session.user.id); redirect("/portal"); }
export async function prepareEmployeeCertificateAction(input: unknown) { const session = await requireEmployeePortal(); const parsed = medicalCertificateUploadSchema.safeParse({ ...(input as object), employeeId: session.employeeId, absenceId: undefined }); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "Dados inválidos." }; try { const result = await prepareMedicalCertificateUpload(parsed.data, session.user.id); return { ok: true as const, key: result.key, uploadUrl: result.uploadUrl }; } catch (error) { return { ok: false as const, message: error instanceof Error ? error.message : "Falha no envio." }; } }
export async function confirmEmployeeCertificateAction(input: unknown) { const session = await requireEmployeePortal(); if (!input || typeof input !== "object" || !("fileKey" in input) || typeof input.fileKey !== "string") return { ok: false as const, message: "Arquivo inválido." }; const parsed = medicalCertificateUploadSchema.safeParse({ ...input, employeeId: session.employeeId, absenceId: undefined }); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "Dados inválidos." }; try { const saved = await confirmMedicalCertificate({ ...parsed.data, fileKey: input.fileKey }, session.user.id, true); await notifyReviewers(session.employeeId, "Novo atestado para análise", `Atestado enviado para o período de ${parsed.data.startDate} a ${parsed.data.endDate}.`, "/gestao/solicitacoes"); return { ok: true as const, id: saved.id }; } catch (error) { return { ok: false as const, message: error instanceof Error ? error.message : "Falha na confirmação." }; } }
