import { AlertTriangle, ArrowLeft, CheckCircle2, History, LockKeyhole, RotateCcw, ScanSearch, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { closeClosingPeriodAction, reopenClosingPeriodAction, sendClosingPeriodToReviewAction } from "@/actions/closing-periods";
import { analyzeClosingPeriod, getClosingPeriod, getClosingPeriodEvents, getClosingPeriodSummaries } from "@/services/closing-period.service";
import { aggregateClosingSummaries } from "@/services/closing-period-core";

const statusLabels = { OPEN: "Aberta", IN_REVIEW: "Em revisão", CLOSED: "Fechada" } as const; const eventLabels = { CREATED: "Competência criada", SENT_TO_REVIEW: "Enviada para revisão", CLOSED: "Competência fechada", REOPENED: "Competência reaberta" } as const;
function month(value: string) { return new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`)); }
function dateTime(value: Date) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Belem" }).format(value); }
function minutes(value: number) { const sign = value < 0 ? "−" : ""; const amount = Math.abs(value); return `${sign}${Math.floor(amount / 60)}h ${String(amount % 60).padStart(2, "0")}min`; }

export default async function ClosingDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { id } = await params; const query = await searchParams; const period = await getClosingPeriod(id); if (!period) notFound();
  const [events, liveAnalysis, frozen] = await Promise.all([getClosingPeriodEvents(id), period.status !== "CLOSED" ? analyzeClosingPeriod(period.startDate, period.endDate) : Promise.resolve(undefined), period.currentRevision ? getClosingPeriodSummaries(id, period.currentRevision) : Promise.resolve([])]);
  const summaries: Array<{ employeeId: string; employeeName: string; registrationNumber: string; plannedMinutes: number; workedMinutes: number; lateMinutes: number; earlyDepartureMinutes: number; overtimeMinutes: number; absenceDays: number; justifiedAbsenceDays: number; timeBankMinutes: number }> = period.status === "CLOSED" ? frozen : liveAnalysis?.summaries ?? []; const blockers = liveAnalysis?.blockers ?? [];
  const totals = aggregateClosingSummaries(summaries);
  return <main className="dashboard-page closing-detail-page"><Link className="back-link" href="/admin/fechamentos"><ArrowLeft size={17} /> Voltar para competências</Link><section className="closing-hero"><div><span><LockKeyhole size={23} /></span><div><p className="eyebrow">Competência</p><h1>{month(period.referenceMonth)}</h1><p>{period.startDate} — {period.endDate} · revisão {period.currentRevision}</p></div></div><span className={`closing-status status-${period.status.toLowerCase()}`}>{statusLabels[period.status]}</span></section>{query.created ? <p className="success-message">Competência criada com sucesso.</p> : null}{query.review ? <p className="success-message">Competência enviada para revisão.</p> : null}{query.closed ? <p className="success-message">Competência fechada e resultados congelados.</p> : null}{query.reopened ? <p className="success-message">Competência reaberta. A revisão anterior foi preservada.</p> : null}{query.error ? <p className="form-error">Não foi possível concluir a transição. Verifique o estado, o motivo e as pendências.</p> : null}
    <section className="closing-actions">{period.status === "OPEN" ? <form action={sendClosingPeriodToReviewAction.bind(null, id)}><button><ScanSearch size={17} /> Enviar para revisão</button></form> : null}{period.status === "IN_REVIEW" ? <form action={closeClosingPeriodAction.bind(null, id)}><button disabled={liveAnalysis?.hasCriticalBlockers}><LockKeyhole size={17} /> Fechar competência</button></form> : null}{period.status === "CLOSED" ? <form className="closing-reopen" action={reopenClosingPeriodAction.bind(null, id)}><input name="reason" minLength={10} maxLength={500} placeholder="Motivo obrigatório da reabertura" required /><button><RotateCcw size={17} /> Reabrir</button></form> : null}<p><ShieldCheck size={16} /> {period.status === "CLOSED" ? "Dados que afetam esta competência estão bloqueados." : "As alterações permanecem permitidas até o fechamento."}</p></section>
    {period.status !== "CLOSED" ? <section className="data-panel closing-blockers"><header><AlertTriangle size={19} /><div><h2>Pendências de fechamento</h2><p>Itens críticos bloqueiam o fechamento; alertas pedem conferência.</p></div></header><div>{blockers.map((blocker) => <article className={blocker.severity.toLowerCase()} key={blocker.code}>{blocker.count ? <AlertTriangle size={18} /> : <CheckCircle2 size={18} />}<span><strong>{blocker.label}</strong><small>{blocker.severity === "CRITICAL" ? "Crítica" : "Alerta"}</small></span><em>{blocker.count}</em></article>)}</div></section> : <p className="closing-frozen-note"><LockKeyhole size={17} /> Exibindo o snapshot imutável da revisão {period.currentRevision}.</p>}
    <section className="closing-totals"><article><span>Atrasos</span><strong>{minutes(totals.late)}</strong></article><article><span>Horas adicionais</span><strong>{minutes(totals.overtime)}</strong></article><article><span>Faltas</span><strong>{totals.absences}</strong></article><article><span>Banco de horas</span><strong>{minutes(totals.bank)}</strong></article></section>
    <section className="data-panel closing-employees"><header><div><h2>Resumo por funcionário</h2><p>{period.status === "CLOSED" ? "Valores congelados no fechamento." : "Prévia calculada com os dados atuais."}</p></div><span>{summaries.length}</span></header>{summaries.length ? <div>{summaries.map((item) => <article key={item.employeeId}><div><strong>{item.employeeName}</strong>{"registrationNumber" in item ? <small>{item.registrationNumber}</small> : null}</div><span><small>Previsto</small><strong>{minutes(item.plannedMinutes)}</strong></span><span><small>Trabalhado</small><strong>{minutes(item.workedMinutes)}</strong></span><span><small>Atraso</small><strong>{minutes(item.lateMinutes)}</strong></span><span><small>Extra</small><strong>{minutes(item.overtimeMinutes)}</strong></span><span><small>Faltas</small><strong>{item.absenceDays}</strong></span><span><small>Banco</small><strong>{minutes(item.timeBankMinutes)}</strong></span></article>)}</div> : <div className="availability-empty">Nenhum resultado disponível para esta competência.</div>}</section>
    <section className="data-panel closing-events"><header><History size={18} /><div><h2>Histórico do workflow</h2><p>Todas as transições permanecem registradas.</p></div></header><div>{events.map((event) => <article key={event.id}><span><strong>{eventLabels[event.event]}</strong><small>{dateTime(event.createdAt)} · {event.performedByName}</small></span><em>{event.fromStatus ? `${statusLabels[event.fromStatus]} → ` : ""}{statusLabels[event.toStatus]}</em>{event.reason ? <p>{event.reason}</p> : null}</article>)}</div></section>
  </main>;
}
