import { desc, eq } from "drizzle-orm";
import { MonitorSmartphone, Radio, ShieldOff } from "lucide-react";
import { blockTerminalAction, generateTerminalActivationAction, reactivateTerminalAction } from "@/actions/terminals";
import { db } from "@/db";
import { establishments, repCollectors, repRegistrars } from "@/db/schema";

function formatDateTime(value: Date) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(value); }

export default async function TerminalsPage({ searchParams }: { searchParams: Promise<{ activation?: string }> }) { const query = await searchParams; const terminals = await db.select({ id: repCollectors.id, name: repCollectors.name, deviceIdentifier: repCollectors.deviceIdentifier, status: repCollectors.status, lastSeenAt: repCollectors.lastSeenAt, terminalVersion: repCollectors.terminalVersion, establishmentName: establishments.name }).from(repCollectors).innerJoin(repRegistrars, eq(repRegistrars.id, repCollectors.registrarId)).innerJoin(establishments, eq(establishments.id, repRegistrars.establishmentId)).orderBy(desc(repCollectors.createdAt)); const onlineLimit = Date.now() - 120_000; return <main className="page-content terminals-page"><header className="page-heading"><div><p className="eyebrow">REP-P</p><h1>Terminais de ponto</h1><p>Controle os dispositivos autorizados para registrar ponto.</p></div></header>{query.activation && <div className="form-alert success"><strong>Código de ativação: {query.activation}</strong><span>Válido por 10 minutos e utilizável uma única vez.</span></div>}<section className="content-panel terminals-panel"><header><div><h2>Dispositivos</h2><p>Status, contato e versão instalada.</p></div><span>{terminals.length} terminal(is)</span></header><div className="terminal-admin-list">{terminals.map((terminal) => { const online = terminal.status === "ACTIVE" && !!terminal.lastSeenAt && terminal.lastSeenAt.getTime() >= onlineLimit; const status = terminal.status === "BLOCKED" ? "Bloqueado" : online ? "Online" : terminal.status === "ACTIVE" ? "Offline" : "Inativo"; return <article key={terminal.id}><span className="terminal-admin-icon"><MonitorSmartphone size={22} /></span><div><strong>{terminal.name}</strong><small>{terminal.deviceIdentifier} · {terminal.establishmentName}</small></div><span className={`terminal-admin-status ${status.toLowerCase()}`}><Radio size={13} /> {status}</span><div className="terminal-admin-meta"><small>Último contato</small><strong>{terminal.lastSeenAt ? formatDateTime(terminal.lastSeenAt) : "Nunca"}</strong></div><div className="terminal-admin-meta"><small>Versão</small><strong>{terminal.terminalVersion ?? "—"}</strong></div><div className="terminal-admin-actions"><form action={generateTerminalActivationAction}><input type="hidden" name="collectorId" value={terminal.id} /><button type="submit">Nova ativação</button></form>{terminal.status === "BLOCKED" ? <form action={reactivateTerminalAction}><input type="hidden" name="collectorId" value={terminal.id} /><button type="submit">Reativar</button></form> : <form action={blockTerminalAction}><input type="hidden" name="collectorId" value={terminal.id} /><button className="danger" type="submit"><ShieldOff size={14} /> Bloquear</button></form>}</div></article>; })}{terminals.length === 0 && <p className="terminal-admin-empty">Nenhum coletor REP-P provisionado.</p>}</div></section></main>; }
