"use client";

import { Clock3, LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useActionState, useState } from "react";
import { generateSimulatedTimeEntriesAction, type TimeEntryFormState } from "@/actions/time-entries";

export function TimeEntrySimulatorForm({ employees, selectedEmployeeId }: { employees: Array<{ id: string; fullName: string; registrationNumber: string }>; selectedEmployeeId?: string }) {
  const [state, action, pending] = useActionState(generateSimulatedTimeEntriesAction, {} as TimeEntryFormState);
  const [times, setTimes] = useState(["08:00", "12:00", "13:00", "17:00"]);
  return <form className="employee-form time-entry-form" action={action}><section className="form-section"><div className="form-section-heading"><span><Clock3 size={20} /></span><div><h2>Dados da simulação</h2><p>As marcações serão originais e não poderão ser editadas ou excluídas.</p></div></div><div className="form-grid time-entry-meta"><div className="field-group"><label htmlFor="employeeId">Funcionário *</label><select id="employeeId" name="employeeId" defaultValue={selectedEmployeeId ?? ""} required><option value="" disabled>Selecione</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName} · {employee.registrationNumber}</option>)}</select></div><div className="field-group"><label htmlFor="date">Data *</label><input id="date" name="date" type="date" required /></div></div></section><section className="form-section"><div className="form-section-heading"><span><Clock3 size={20} /></span><div><h2>Horários oficiais</h2><p>Informe de uma a oito marcações no fuso de Belém.</p></div></div><div className="time-entry-times">{times.map((time, index) => <div className="field-group" key={index}><label htmlFor={`time-${index}`}>Marcação {index + 1}</label><div><input id={`time-${index}`} name="times" type="time" value={time} onChange={(event) => setTimes((current) => current.map((item, position) => position === index ? event.target.value : item))} required /><button aria-label={`Remover marcação ${index + 1}`} disabled={times.length === 1} type="button" onClick={() => setTimes((current) => current.filter((_, position) => position !== index))}><Trash2 size={16} /></button></div></div>)}{times.length < 8 ? <button className="time-entry-add" type="button" onClick={() => setTimes((current) => [...current, ""])}><Plus size={16} /> Adicionar horário</button> : null}</div></section>{state.message ? <div className="form-error" role="alert"><strong>{state.message}</strong>{state.errors?.length ? <ul>{state.errors.map((error) => <li key={error}>{error}</li>)}</ul> : null}</div> : null}<div className="form-actions"><Link className="cancel-button" href="/admin/marcacoes">Cancelar</Link><button className="primary-button action-button" disabled={pending} type="submit">{pending ? <LoaderCircle className="spin" size={18} /> : <Save size={18} />}{pending ? "Gerando..." : "Gerar marcações"}</button></div></form>;
}
