import { and, eq, gt, isNull } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { biometricValidations, locationValidations, offlinePointOperations, pointRegistrationAttempts, securityEvents, timeEntries } from "@/db/schema";
import { contingencyPolicy } from "@/modules/attendance-contingency/policies/contingency-policy.service";
import { recordRepPEvent } from "@/rep-p/audit.service";
import { verifyContingencyTicket } from "@/rep-p/contingency-ticket";
import { RepPRegistrationError } from "@/rep-p/registration-core";
import { registerRepPPoint } from "@/services/rep-p-registration.service";
import { authenticateTerminal } from "@/services/terminal-auth.service";
export const runtime = "nodejs";
const schema = z.object({ eventType: z.enum(["CLOCK_IN", "CLOCK_OUT"]), locationValidationId: z.uuid(), biometricValidationId: z.uuid(), attemptId: z.uuid(), contingencyTicket: z.string().max(4_000).optional(), capturedAt: z.iso.datetime().optional(), operationId: z.uuid().optional(), clockEvidence: z.object({ lastServerTime: z.iso.datetime().optional(), lastClockSyncAt: z.iso.datetime().optional(), clockOffsetMs: z.number().int().max(86_400_000).min(-86_400_000).optional(), offlineStartedAt: z.iso.datetime().optional(), timeZone: z.string().max(80).optional() }).passthrough().optional() }).strict();
const idempotencySchema = z.string().min(16).max(100).regex(/^[A-Za-z0-9_-]+$/);
export async function POST(request: Request) {
  const collector = await authenticateTerminal(); if (!collector) return Response.json({ error: "Terminal não autorizado." }, { status: 401 });
  const input = schema.safeParse(await request.json().catch(() => null)); const idempotencyKey = idempotencySchema.safeParse(request.headers.get("idempotency-key")); if (!input.success || !idempotencyKey.success) return Response.json({ error: "Solicitação inválida." }, { status: 400 });
  const now = new Date(); const ticket = input.data.contingencyTicket ? verifyContingencyTicket(input.data.contingencyTicket, collector.id, now) : undefined; const capturedAt = input.data.capturedAt ? new Date(input.data.capturedAt) : undefined;
  if (input.data.contingencyTicket && (!ticket || !capturedAt || capturedAt < new Date(ticket.issuedAt) || capturedAt > new Date(ticket.expiresAt) || capturedAt.getTime() > now.getTime() + 120_000)) { await recordRepPEvent(db, { eventType: "CONTINGENCY_REJECTED", outcome: "REJECTED", collectorId: collector.id, reasonCode: "INVALID_TICKET_OR_CLOCK" }); return Response.json({ error: "Ticket de contingência inválido, expirado ou com horário inconsistente." }, { status: 422 }); }
  if (ticket && (ticket.attemptId !== input.data.attemptId || ticket.locationValidationId !== input.data.locationValidationId || ticket.biometricValidationId !== input.data.biometricValidationId)) return Response.json({ error: "As evidências da contingência não correspondem." }, { status: 422 });
  const [existing] = await db.select({ employeeId: timeEntries.employeeId }).from(timeEntries).where(and(eq(timeEntries.collectorId, collector.id), eq(timeEntries.idempotencyKey, idempotencyKey.data))).limit(1); if (existing) { const result = await registerRepPPoint({ employeeId: existing.employeeId, collectorId: collector.id, eventType: input.data.eventType, idempotencyKey: idempotencyKey.data }); return Response.json(result, { status: 200, headers: { "Cache-Control": "no-store" } }); }
  const conditions = [eq(pointRegistrationAttempts.id, input.data.attemptId), eq(pointRegistrationAttempts.collectorId, collector.id), eq(pointRegistrationAttempts.locationValidationId, input.data.locationValidationId), eq(pointRegistrationAttempts.biometricValidationId, input.data.biometricValidationId)]; if (!ticket) conditions.push(eq(pointRegistrationAttempts.status, "BIOMETRIC_APPROVED"), gt(pointRegistrationAttempts.expiresAt, now));
  const [attempt] = await db.select({ id: pointRegistrationAttempts.id }).from(pointRegistrationAttempts).where(and(...conditions)).limit(1); if (!attempt) return Response.json({ error: "Tentativa inválida ou expirada." }, { status: 422 });
  const biometricConditions = [eq(biometricValidations.id, input.data.biometricValidationId), eq(biometricValidations.attemptId, attempt.id), eq(biometricValidations.collectorId, collector.id), eq(biometricValidations.matchStatus, "APPROVED"), isNull(biometricValidations.usedAt)]; if (!ticket) biometricConditions.push(gt(biometricValidations.expiresAt, now));
  const [biometric] = await db.update(biometricValidations).set({ usedAt: now }).where(and(...biometricConditions)).returning({ employeeId: biometricValidations.employeeId }); const employeeId = biometric?.employeeId; if (!employeeId || (ticket && employeeId !== ticket.employeeId)) return Response.json({ error: "Biometria inválida ou já utilizada." }, { status: 422 });
  try { await db.update(pointRegistrationAttempts).set({ status: "REGISTERING" }).where(eq(pointRegistrationAttempts.id, attempt.id)); const result = await registerRepPPoint({ employeeId, eventType: input.data.eventType, collectorId: collector.id, idempotencyKey: idempotencyKey.data, locationValidationId: input.data.locationValidationId, biometricValidationId: input.data.biometricValidationId, registrationAttemptId: attempt.id, trustedOccurredAt: ticket ? capturedAt : undefined, contingency: Boolean(ticket && now.getTime() - new Date(ticket.issuedAt).getTime() > 30_000) }); await db.update(pointRegistrationAttempts).set({ status: "COMPLETED", completedAt: now }).where(eq(pointRegistrationAttempts.id, attempt.id)); await db.update(locationValidations).set({ evidence: { source: "DEVICE_GEOLOCATION", timeEntryId: result.id, nsr: result.nsr, attemptId: attempt.id, synchronized: Boolean(ticket) } }).where(eq(locationValidations.id, input.data.locationValidationId)); if (ticket) await recordRepPEvent(db, { eventType: "CONTINGENCY_SYNCHRONIZED", outcome: "SUCCESS", collectorId: collector.id, employeeId, nsr: result.nsr, metadata: { attemptId: attempt.id, delayMs: now.getTime() - capturedAt!.getTime() } }); return Response.json({ ...result, attemptId: attempt.id }, { status: result.replay ? 200 : 201, headers: { "Cache-Control": "no-store" } }); }
  catch (error) { await db.update(pointRegistrationAttempts).set({ status: "FAILED", failureReason: "REGISTRATION_FAILED", completedAt: now }).where(eq(pointRegistrationAttempts.id, attempt.id)); if (error instanceof RepPRegistrationError) return Response.json({ error: error.message, code: error.code }, { status: 422 }); return Response.json({ error: "Não foi possível registrar o ponto." }, { status: 500 }); }
}
