import { and, desc, eq, gt, isNull } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { biometricValidations, locationValidations, offlinePointOperations, pointRegistrationAttempts, securityEvents, timeEntries } from "@/db/schema";
import { contingencyPolicy } from "@/modules/attendance-contingency/policies/contingency-policy.service";
import { recordRepPEvent } from "@/rep-p/audit.service";
import { verifyContingencyTicket } from "@/rep-p/contingency-ticket";
import { RepPRegistrationError } from "@/rep-p/registration-core";
import { registerRepPPoint } from "@/services/rep-p-registration.service";
import { authenticateTerminal } from "@/services/terminal-auth.service";
export const runtime = "nodejs";
const clockEvidenceSchema = z.object({ lastServerTime: z.iso.datetime().optional(), lastClockSyncAt: z.iso.datetime().optional(), clockOffsetMs: z.number().int().min(-86_400_000).max(86_400_000).optional(), offlineStartedAt: z.iso.datetime().optional(), timeZone: z.string().max(80).optional() }).passthrough();
const schema = z.object({ eventType: z.enum(["CLOCK_IN", "CLOCK_OUT"]), locationValidationId: z.uuid(), biometricValidationId: z.uuid(), attemptId: z.uuid(), contingencyTicket: z.string().max(4_000).optional(), capturedAt: z.iso.datetime().optional(), operationId: z.uuid().optional(), clockEvidence: clockEvidenceSchema.optional() }).strict();
const idempotencySchema = z.string().min(16).max(100).regex(/^[A-Za-z0-9_-]+$/);
async function trackOperation(input: z.infer<typeof schema>, collectorId: string, employeeId: string | undefined, status: "SYNCING" | "ACCEPTED" | "REJECTED" | "REQUIRES_REVIEW", timeEntryId?: string, flags: string[] = []) { if (!input.operationId || !input.capturedAt) return; await db.insert(offlinePointOperations).values({ operationId: input.operationId, collectorId, employeeId, status, deviceCapturedAt: new Date(input.capturedAt), lastServerTime: input.clockEvidence?.lastServerTime ? new Date(input.clockEvidence.lastServerTime) : null, lastClockSyncAt: input.clockEvidence?.lastClockSyncAt ? new Date(input.clockEvidence.lastClockSyncAt) : null, clockOffsetMs: input.clockEvidence?.clockOffsetMs, riskFlags: flags, timeEntryId, resolvedAt: ["ACCEPTED", "REJECTED"].includes(status) ? new Date() : null }).onConflictDoUpdate({ target: offlinePointOperations.operationId, set: { employeeId, status, retryCount: 1, riskFlags: flags, timeEntryId, resolvedAt: ["ACCEPTED", "REJECTED"].includes(status) ? new Date() : null } }); }
export async function POST(request: Request) {
  const collector = await authenticateTerminal(); if (!collector) return Response.json({ error: "COLLECTOR_UNAUTHORIZED" }, { status: 401 });
  const input = schema.safeParse(await request.json().catch(() => null)); const key = idempotencySchema.safeParse(request.headers.get("idempotency-key")); if (!input.success || !key.success) return Response.json({ error: "Solicitação inválida." }, { status: 400 });
  const now = new Date(); const ticket = input.data.contingencyTicket ? verifyContingencyTicket(input.data.contingencyTicket, collector.id, now) : undefined; const deviceCapturedAt = input.data.capturedAt ? new Date(input.data.capturedAt) : undefined; const offsetMs = input.data.clockEvidence?.clockOffsetMs ?? 0; const correctedAt = deviceCapturedAt ? new Date(deviceCapturedAt.getTime() + offsetMs) : undefined; const delayed = Boolean(ticket && correctedAt && now.getTime() - correctedAt.getTime() > 30_000); const risks: string[] = [];
  if (Math.abs(offsetMs) > contingencyPolicy.clockDriftWarningMs) risks.push("CLOCK_DRIFT_HIGH"); if (input.data.clockEvidence?.timeZone && input.data.clockEvidence.timeZone !== "America/Belem") risks.push("DEVICE_TIMEZONE_MISMATCH");
  if (input.data.contingencyTicket && (!ticket || !deviceCapturedAt || !correctedAt || correctedAt < new Date(ticket.issuedAt) || correctedAt > new Date(ticket.expiresAt) || correctedAt.getTime() > now.getTime() + contingencyPolicy.clockDriftWarningMs)) { await trackOperation(input.data, collector.id, ticket?.employeeId, "REJECTED", undefined, [...risks, "TIME_ROLLBACK_DETECTED"]); await db.insert(securityEvents).values({ type: "CLOCK_MANIPULATION", severity: "WARNING", collectorId: collector.id, metadataSafe: { operationId: input.data.operationId, offsetMs } }); await recordRepPEvent(db, { eventType: "CONTINGENCY_REJECTED", outcome: "REJECTED", collectorId: collector.id, reasonCode: "INVALID_TICKET_OR_CLOCK" }); return Response.json({ error: "Ticket expirado ou horário inconsistente." }, { status: 422 }); }
  if (ticket && (ticket.attemptId !== input.data.attemptId || ticket.locationValidationId !== input.data.locationValidationId || ticket.biometricValidationId !== input.data.biometricValidationId)) return Response.json({ error: "Evidências não correspondem." }, { status: 422 });
  const [existing] = await db.select({ id: timeEntries.id, employeeId: timeEntries.employeeId }).from(timeEntries).where(and(eq(timeEntries.collectorId, collector.id), eq(timeEntries.idempotencyKey, key.data))).limit(1); if (existing) { const result = await registerRepPPoint({ employeeId: existing.employeeId, collectorId: collector.id, eventType: input.data.eventType, idempotencyKey: key.data }); await trackOperation(input.data, collector.id, existing.employeeId, "ACCEPTED", existing.id, risks); return Response.json(result, { status: 200 }); }
  const attemptConditions = [eq(pointRegistrationAttempts.id, input.data.attemptId), eq(pointRegistrationAttempts.collectorId, collector.id), eq(pointRegistrationAttempts.locationValidationId, input.data.locationValidationId), eq(pointRegistrationAttempts.biometricValidationId, input.data.biometricValidationId)]; if (!ticket) attemptConditions.push(eq(pointRegistrationAttempts.status, "BIOMETRIC_APPROVED"), gt(pointRegistrationAttempts.expiresAt, now)); const [attempt] = await db.select({ id: pointRegistrationAttempts.id }).from(pointRegistrationAttempts).where(and(...attemptConditions)).limit(1); if (!attempt) return Response.json({ error: "Tentativa inválida ou expirada." }, { status: 422 });
  const biometricConditions = [eq(biometricValidations.id, input.data.biometricValidationId), eq(biometricValidations.attemptId, attempt.id), eq(biometricValidations.collectorId, collector.id), eq(biometricValidations.matchStatus, "APPROVED"), isNull(biometricValidations.usedAt)]; if (!ticket) biometricConditions.push(gt(biometricValidations.expiresAt, now)); const [biometric] = await db.update(biometricValidations).set({ usedAt: now }).where(and(...biometricConditions)).returning({ employeeId: biometricValidations.employeeId }); const employeeId = biometric?.employeeId; if (!employeeId || (ticket && employeeId !== ticket.employeeId)) { await db.insert(securityEvents).values({ type: "REPLAY", severity: "WARNING", collectorId: collector.id, attemptId: attempt.id, metadataSafe: { operationId: input.data.operationId } }); return Response.json({ error: "REPLAY_REJECTED" }, { status: 409 }); }
  await trackOperation(input.data, collector.id, employeeId, "SYNCING", undefined, risks);
  try { const [previous] = await db.select({ occurredAt: timeEntries.occurredAt }).from(timeEntries).where(eq(timeEntries.employeeId, employeeId)).orderBy(desc(timeEntries.occurredAt)).limit(1); const duplicate = Boolean(previous && correctedAt && Math.abs(correctedAt.getTime() - previous.occurredAt.getTime()) <= contingencyPolicy.temporalDuplicateWindowMs); if (duplicate) { risks.push("POTENTIAL_DUPLICATE"); await db.insert(securityEvents).values({ type: "POTENTIAL_DUPLICATE", severity: "WARNING", collectorId: collector.id, employeeId, attemptId: attempt.id, metadataSafe: { operationId: input.data.operationId } }); }
    const result = await registerRepPPoint({ employeeId, eventType: input.data.eventType, collectorId: collector.id, idempotencyKey: key.data, locationValidationId: input.data.locationValidationId, biometricValidationId: input.data.biometricValidationId, registrationAttemptId: attempt.id, trustedOccurredAt: delayed ? correctedAt : undefined, contingency: delayed }); await db.update(pointRegistrationAttempts).set({ status: "COMPLETED", completedAt: now }).where(eq(pointRegistrationAttempts.id, attempt.id)); await db.update(locationValidations).set({ evidence: { source: "DEVICE_GEOLOCATION", timeEntryId: result.id, nsr: result.nsr, attemptId: attempt.id, synchronized: delayed } }).where(eq(locationValidations.id, input.data.locationValidationId)); await trackOperation(input.data, collector.id, employeeId, duplicate ? "REQUIRES_REVIEW" : "ACCEPTED", result.id, risks); if (delayed) await recordRepPEvent(db, { eventType: "CONTINGENCY_SYNCHRONIZED", outcome: "SUCCESS", collectorId: collector.id, employeeId, nsr: result.nsr, metadata: { attemptId: attempt.id, delayMs: now.getTime() - correctedAt!.getTime(), risks } }); return Response.json({ ...result, reconciliationStatus: duplicate ? "REQUIRES_REVIEW" : "ACCEPTED" }, { status: result.replay ? 200 : 201 });
  } catch (error) { await trackOperation(input.data, collector.id, employeeId, "REQUIRES_REVIEW", undefined, [...risks, "BACKEND_FAILURE"]); if (error instanceof RepPRegistrationError) return Response.json({ error: error.message, code: error.code }, { status: 422 }); return Response.json({ error: "Não foi possível registrar o ponto." }, { status: 500 }); }
}
