import { CalendarCheck2, ChevronRight, LockKeyhole, Plus, ScanSearch } from "lucide-react";
import Link from "next/link";
import { createClosingPeriodAction } from "@/actions/closing-periods";
import { listClosingPeriods } from "@/services/closing-period.service";

const statusLabels = { OPEN: "Aberta", IN_REVIEW: "Em revisão", CLOSED: "Fechada" } as const;
function month(value: string) { return new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`)); }
function dateTime(value: Date | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Belem" }).format(value) : "—"; }

export default async function ClosingsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const periods = await listClosingPeriods(); const closed = periods.filter((item) => item.status === "CLOSED").length; const review = periods.filter((item) => item.status === "IN_REVIEW").length;
  return <main className="dashboard-page closing-page"><div className="page-heading employees-heading"><div><p className="eyebrow">Consolidação mensal</p><h1>Fechamento de competência</h1><p>Revise pendências, congele resultados e preserve cada reabertura.</p></div><form className="closing-create" action={createClosingPeriodAction}><input name="referenceMonth" type="month" required /><button><Plus size={17} /> Nova competência</button></form></div>{query.error ? <p className="form-error">Não foi possível criar a competência. Verifique o mês ou se ela já existe.</p> : null}<section className="closing-summary"><article><CalendarCheck2 size={20} /><span><strong>{periods.length}</strong><small>Competências</small></span></article><article><ScanSearch size={20} /><span><strong>{review}</strong><small>Em revisão</small></span></article><article><LockKeyhole size={20} /><span><strong>{closed}</strong><small>Fechadas</small></span></article></section><section className="data-panel closing-list-panel"><header><div><h2>Histórico de competências</h2><p>Abra uma competência para consultar pendências, resumo e eventos.</p></div></header>{periods.length ? <div className="closing-list">{periods.map((period) => <Link href={`/admin/fechamentos/${period.id}`} key={period.id}><span className={`closing-status status-${period.status.toLowerCase()}`}>{statusLabels[period.status]}</span><div><strong>{month(period.referenceMonth)}</strong><small>{period.startDate} — {period.endDate}</small></div><div><small>Revisão congelada</small><strong>{period.currentRevision || "Nenhuma"}</strong></div><div><small>Fechada em</small><strong>{dateTime(period.closedAt)}</strong></div><ChevronRight size={18} /></Link>)}</div> : <div className="empty-state"><CalendarCheck2 size={30} /><h2>Nenhuma competência criada</h2><p>Crie a primeira competência mensal para iniciar a conferência.</p></div>}</section></main>;
}
