import { ArrowLeft, ArrowRightLeft, BriefcaseBusiness, CalendarDays, CalendarRange, Clock3, Edit3, FileText, Hash, Phone, PhoneCall, Plus, Umbrella, UserRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { EmployeeActiveForm } from "@/components/employees/employee-active-form";
import { EmployeeStatusBadge } from "@/components/employees/employee-status-badge";
import { getEmployeeAvailability } from "@/services/availability.service";
import { getEmployeeById, listEmployeeDocuments } from "@/services/employee.service";
import { listEmployeeTimeEntries } from "@/services/time-entry.service";
import { listWorkSchedulesByEmployee } from "@/services/work-schedule.service";
import { formatCpf, formatDate, formatPhone } from "@/utils/format";
import { employeeIdSchema } from "@/validations/employee";

type Tab = "overview" | "schedules" | "availability" | "documents" | "timesheet";
const tabs: Array<{ id: Tab; label: string; icon: typeof UserRound }> = [
  { id: "overview", label: "Visão geral", icon: UserRound }, { id: "schedules", label: "Jornadas e escalas", icon: CalendarRange },
  { id: "availability", label: "Folgas e ausências", icon: Umbrella }, { id: "documents", label: "Documentos", icon: FileText },
  { id: "timesheet", label: "Espelho de ponto", icon: Clock3 },
];
const swapLabels = { PENDING: "Pendente", APPROVED: "Aprovada", REJECTED: "Rejeitada" } as const;
const leaveLabels = { MEDICAL: "Médico", PERSONAL: "Pessoal", LEGAL: "Legal", OTHER: "Outro" } as const;

function Info({ label, value, icon }: { label: string; value: string; icon?: ReactNode }) { return <div className="employee-profile-field"><dt>{icon}{label}</dt><dd>{value}</dd></div>; }
function Empty({ icon, title, text, action }: { icon: ReactNode; title: string; text: string; action?: ReactNode }) { return <div className="employee-tab-empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p>{action}</div>; }

export default async function EmployeeDetailPage({ params, searchParams }: PageProps<"/admin/funcionarios/[id]">) {
  const { id } = await params;
  const parsedId = employeeIdSchema.safeParse(id);
  if (!parsedId.success) notFound();
  const [employee, schedules, availability, documents, timeEntries] = await Promise.all([getEmployeeById(id), listWorkSchedulesByEmployee(id), getEmployeeAvailability(id), listEmployeeDocuments(id), listEmployeeTimeEntries(id)]);
  if (!employee) notFound();
  const query = await searchParams;
  const tab: Tab = tabs.some((item) => item.id === query.tab) ? query.tab as Tab : "overview";
  const initials = employee.fullName.split(" ").slice(0, 2).map((part) => part[0]).join("").toUpperCase();

  return <main className="dashboard-page employee-profile-page">
    <Link className="back-link" href="/admin/funcionarios"><ArrowLeft size={17} /> Voltar para funcionários</Link>
    {query.updated === "1" ? <p className="success-message">Dados atualizados com sucesso.</p> : null}
    {query.deactivated === "1" ? <p className="success-message neutral">Funcionário inativado. O histórico foi preservado.</p> : null}
    {query.reactivated === "1" ? <p className="success-message">Funcionário reativado com sucesso.</p> : null}
    <section className="employee-profile-hero"><div className="employee-profile-person"><span className="employee-profile-avatar">{initials}</span><div className="employee-profile-title"><div><h1>{employee.fullName}</h1><EmployeeStatusBadge status={employee.status} /></div><p>{employee.position}<span aria-hidden="true">•</span>Matrícula {employee.registrationNumber}</p></div></div><div className="employee-profile-actions"><Link className="secondary-button detail-action" href={`/admin/funcionarios/${employee.id}/editar`}><Edit3 size={17} /> Editar dados</Link><EmployeeActiveForm employeeId={employee.id} active={employee.isActive} /></div></section>
    <nav className="employee-profile-tabs" aria-label="Áreas do funcionário">{tabs.map(({ id: tabId, label, icon: Icon }) => <Link className={tab === tabId ? "active" : ""} href={`/admin/funcionarios/${id}?tab=${tabId}`} key={tabId}><Icon size={16} />{label}</Link>)}</nav>

    {tab === "overview" ? <div className="employee-profile-layout"><div className="employee-profile-main"><section className="employee-profile-card"><header><span><UserRound size={19} /></span><div><h2>Dados pessoais</h2><p>Identificação e contato</p></div></header><dl className="employee-profile-fields"><Info label="Nome completo" value={employee.fullName} /><Info label="CPF" value={formatCpf(employee.cpf)} /><Info label="Telefone" value={employee.phone ? formatPhone(employee.phone) : "Não informado"} icon={<Phone size={14} />} /></dl></section><section className="employee-profile-card"><header><span><BriefcaseBusiness size={19} /></span><div><h2>Dados profissionais</h2><p>Informações do vínculo</p></div></header><dl className="employee-profile-fields"><Info label="Matrícula" value={employee.registrationNumber} icon={<Hash size={14} />} /><Info label="Cargo" value={employee.position} /><Info label="Data de admissão" value={formatDate(employee.admissionDate)} icon={<CalendarDays size={14} />} /><Info label="Carteira de trabalho" value={employee.workCardNumber ?? "Não informada"} /></dl></section></div><aside className="employee-profile-side"><section className="employee-profile-card"><header><span><PhoneCall size={19} /></span><div><h2>Contato de emergência</h2><p>Pessoa para situações urgentes</p></div></header>{employee.emergencyContactName || employee.emergencyContactPhone ? <dl><Info label="Nome" value={employee.emergencyContactName ?? "Não informado"} /><Info label="Parentesco ou relação" value={employee.emergencyContactRelationship ?? "Não informado"} /><Info label="Telefone" value={employee.emergencyContactPhone ? formatPhone(employee.emergencyContactPhone) : "Não informado"} icon={<Phone size={14} />} /></dl> : <div className="employee-profile-empty">Nenhum contato de emergência informado.</div>}</section><section className="employee-profile-card employee-summary-card"><header><span><CalendarRange size={19} /></span><div><h2>Resumo operacional</h2><p>Registros relacionados</p></div></header><dl><Info label="Jornadas" value={String(schedules.length)} /><Info label="Folgas e ausências" value={String(availability.daysOff.length + availability.swaps.length + availability.vacations.length + availability.leaves.length)} /><Info label="Documentos" value={String(documents.length)} /></dl></section></aside></div> : null}

    {tab === "schedules" ? <section className="employee-tab-panel"><header><div><h2>Jornadas e escalas</h2><p>Histórico de vigências e acesso ao calendário individual.</p></div><div><Link className="secondary-button detail-action" href={`/admin/escalas?employeeId=${id}&view=month`}><CalendarDays size={16} /> Ver calendário</Link><Link className="primary-button action-button" href={`/admin/jornadas/nova?employeeId=${id}`}><Plus size={16} /> Nova jornada</Link></div></header>{schedules.length ? <div className="employee-related-list">{schedules.map((schedule) => <Link href={`/admin/jornadas/${schedule.id}`} key={schedule.id}><span><CalendarRange size={18} /></span><div><strong>{schedule.name}</strong><small>{formatDate(schedule.validFrom)} — {schedule.validTo ? formatDate(schedule.validTo) : "sem data final"}</small></div><em>Ver detalhes</em></Link>)}</div> : <Empty icon={<CalendarRange size={26} />} title="Nenhuma jornada cadastrada" text="Cadastre a primeira jornada para gerar a previsão deste funcionário." action={<Link className="primary-button action-button" href={`/admin/jornadas/nova?employeeId=${id}`}>Cadastrar jornada</Link>} />}</section> : null}

    {tab === "availability" ? <section className="employee-tab-panel"><header><div><h2>Folgas e ausências</h2><p>Folgas, trocas, férias e afastamentos deste funcionário.</p></div><Link className="primary-button action-button" href={`/admin/disponibilidade/nova?employeeId=${id}`}><Plus size={16} /> Novo registro</Link></header>{availability.daysOff.length + availability.swaps.length + availability.vacations.length + availability.leaves.length ? <div className="employee-availability-groups"><Related title="Folgas" icon={<CalendarDays size={18} />} items={availability.daysOff.map((item) => ({ id: item.id, primary: formatDate(item.date), secondary: item.reason }))} /><Related title="Trocas" icon={<ArrowRightLeft size={18} />} items={availability.swaps.map((item) => ({ id: item.id, primary: `${formatDate(item.dayOffDate)} → ${formatDate(item.workDate)}`, secondary: `${swapLabels[item.status]} · ${item.reason}` }))} /><Related title="Férias" icon={<Umbrella size={18} />} items={availability.vacations.map((item) => ({ id: item.id, primary: `${formatDate(item.startDate)} — ${formatDate(item.endDate)}`, secondary: item.reason }))} /><Related title="Afastamentos" icon={<PhoneCall size={18} />} items={availability.leaves.map((item) => ({ id: item.id, primary: `${formatDate(item.startDate)} — ${formatDate(item.endDate)}`, secondary: `${leaveLabels[item.type]} · ${item.reason}` }))} /></div> : <Empty icon={<Umbrella size={26} />} title="Nenhuma folga ou ausência" text="Os registros de disponibilidade deste funcionário aparecerão aqui." action={<Link className="primary-button action-button" href={`/admin/disponibilidade/nova?employeeId=${id}`}>Adicionar registro</Link>} />}</section> : null}

    {tab === "documents" ? <section className="employee-tab-panel"><header><div><h2>Documentos</h2><p>Arquivos e comprovantes vinculados ao funcionário.</p></div><Link className="primary-button action-button" href={`/admin/atestados/novo?employeeId=${id}`}><Plus size={16} /> Novo atestado</Link></header>{documents.length ? <div className="employee-related-list">{documents.map((document) => <div className="employee-document-row" key={document.id}><span><FileText size={18} /></span><div><strong>{document.title}</strong><small>{document.type} · {document.fileName}</small></div><em>{formatDate(document.createdAt.toISOString().slice(0, 10))}</em>{document.downloadPath ? <a className="employee-document-open" href={document.downloadPath} target="_blank" rel="noreferrer">Visualizar</a> : null}</div>)}</div> : <Empty icon={<FileText size={26} />} title="Nenhum documento anexado" text="Atestados e outros documentos protegidos aparecerão aqui." action={<Link className="primary-button action-button" href={`/admin/atestados/novo?employeeId=${id}`}>Anexar atestado</Link>} />}</section> : null}

    {tab === "timesheet" ? <section className="employee-tab-panel"><header><div><h2>Marcações de ponto</h2><p>Registros originais mais recentes deste funcionário.</p></div><div><Link className="secondary-button detail-action" href={`/admin/marcacoes?employeeId=${id}`}><Clock3 size={16} /> Ver todas</Link><Link className="primary-button action-button" href={`/admin/marcacoes/simular?employeeId=${id}`}><Plus size={16} /> Simular</Link></div></header>{timeEntries.length ? <div className="employee-time-entries">{timeEntries.map((entry) => <div key={entry.id}><span><Clock3 size={17} /></span><strong>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Belem" }).format(entry.occurredAt)}</strong><small>{entry.source === "SIMULATOR" ? "Simulador" : entry.source === "IMPORT" ? "Importação" : "REP-C"}</small></div>)}</div> : <Empty icon={<Clock3 size={26} />} title="Nenhuma marcação registrada" text="As marcações originais deste funcionário aparecerão aqui. Use o simulador apenas no ambiente de desenvolvimento." action={<Link className="primary-button action-button" href={`/admin/marcacoes/simular?employeeId=${id}`}>Simular marcações</Link>} />}</section> : null}
  </main>;
}

function Related({ title, icon, items }: { title: string; icon: ReactNode; items: Array<{ id: string; primary: string; secondary: string }> }) { if (!items.length) return null; return <section className="employee-related-group"><header>{icon}<h3>{title}</h3><span>{items.length}</span></header>{items.map((item) => <div key={item.id}><strong>{item.primary}</strong><small>{item.secondary}</small></div>)}</section>; }
