"use client";

import { useEffect, useReducer, useRef, useState } from "react";
import { CheckCircle2, CloudOff, LoaderCircle, ScanFace, ShieldAlert } from "lucide-react";
import { initialTerminalFlowState, terminalFlowReducer } from "@/terminal/flow-machine";
import type { IdentifiedEmployee } from "@/terminal/identification";
import { SynchronizedClock } from "./synchronized-clock";
import { TerminalFaceCapture } from "./terminal-face-capture";

export function TerminalApp({ developmentEmployees = [] }: { developmentEmployees?: IdentifiedEmployee[] }) { const [state, dispatch] = useReducer(terminalFlowReducer, initialTerminalFlowState); const [online, setOnline] = useState(true); const [authorized, setAuthorized] = useState<boolean | null>(null); const [blocked, setBlocked] = useState(false); const [collectorName, setCollectorName] = useState<string>(); const [code, setCode] = useState(""); const requestId = useRef("");
  const submitting = useRef(false);
  async function heartbeat() { try { const response = await fetch("/api/rep-p/collectors/heartbeat", { method: "POST", cache: "no-store", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ appVersion: "1.0.0" }) }); setOnline(true); const data = await response.json(); setAuthorized(response.ok); setBlocked(data.status === "BLOCKED"); if (response.ok) setCollectorName(data.collector.name); } catch { setOnline(false); } }
  useEffect(() => { const initial = window.setTimeout(heartbeat, 0); const timer = window.setInterval(heartbeat, 30_000); const onOnline = () => heartbeat(); const onOffline = () => setOnline(false); window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); return () => { window.clearTimeout(initial); window.clearInterval(timer); window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, []);
  useEffect(() => { if (!state.employee) return; const timer = window.setTimeout(() => dispatch({ type: "RESET" }), state.status === "SUCCESS" ? 5_000 : 30_000); return () => window.clearTimeout(timer); }, [state.employee, state.status]);
  async function activate(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/rep-p/collectors/activate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); if (response.ok) await heartbeat(); }
  function identify(employee: IdentifiedEmployee) { dispatch({ type: "IDENTIFIED", employee }); window.setTimeout(() => dispatch({ type: "VALIDATED" }), 0); }
  async function requestLocation() { if (!("geolocation" in navigator)) { dispatch({ type: "LOCATION_REJECTED", message: "Localização indisponível neste dispositivo." }); return; } navigator.geolocation.getCurrentPosition(async (position) => { dispatch({ type: "LOCATION_CAPTURED" }); try { const response = await fetch("/api/rep-p/terminal/location", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: position.coords.accuracy, capturedAt: new Date(position.timestamp).toISOString(), source: "DEVICE_GEOLOCATION" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.status === "OUTSIDE_GEOFENCE" ? "Este terminal está fora da área permitida." : data.status === "LOW_ACCURACY" ? "A localização obtida não possui precisão suficiente." : "Não foi possível validar a localização."); dispatch({ type: "LOCATION_VALID", validationId: data.id }); } catch (error) { dispatch({ type: "LOCATION_REJECTED", message: error instanceof Error ? error.message : "Localização indisponível." }); } }, (error) => dispatch({ type: "LOCATION_REJECTED", message: error.code === error.PERMISSION_DENIED ? "A permissão de localização é necessária para registrar o ponto." : error.code === error.TIMEOUT ? "O tempo para obter a localização expirou." : "Localização indisponível." }), { enableHighAccuracy: true, timeout: 15_000, maximumAge: 0 }); }
  useEffect(() => { if (state.status !== "REQUESTING_LOCATION") return; const timer = window.setTimeout(requestLocation, 0); return () => window.clearTimeout(timer); }, [state.status]);
  async function register(eventType: "CLOCK_IN" | "CLOCK_OUT") { if (!state.employee || !state.locationValidationId || !state.biometricValidationId || !state.attemptId || state.status !== "READY" || submitting.current) return; submitting.current = true; dispatch({ type: "REGISTER" }); requestId.current ||= crypto.randomUUID(); try { const response = await fetch("/api/rep-p/terminal/entries", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestId.current }, body: JSON.stringify({ eventType, locationValidationId: state.locationValidationId, biometricValidationId: state.biometricValidationId, attemptId: state.attemptId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível registrar o ponto."); dispatch({ type: "SUCCEEDED", result: { eventLabel: eventType === "CLOCK_IN" ? "Entrada registrada" : "Saída registrada", recordedAt: data.recordedAt, nsr: data.nsr } }); } catch (error) { dispatch({ type: "FAILED", message: error instanceof Error ? error.message : "Servidor indisponível." }); } finally { requestId.current = ""; submitting.current = false; } }
  if (authorized === null) return <section className="point-terminal"><div className="point-terminal-center"><LoaderCircle className="spin" /><strong>Conectando ao terminal…</strong></div></section>;
  if (!authorized) return <section className="point-terminal"><header><ShieldAlert /><div><p>UpTime</p><h1>Ativar terminal</h1></div></header><form className="point-terminal-activation" onSubmit={activate}><label htmlFor="activation-code">Código de ativação</label><input id="activation-code" inputMode="numeric" maxLength={6} pattern="[0-9]{6}" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} /><button className="point-terminal-primary" disabled={code.length !== 6}>Ativar dispositivo</button></form></section>;
  if (blocked) return <section className="point-terminal"><div className="point-terminal-center"><ShieldAlert size={42} /><strong>Terminal indisponível</strong><p>Entre em contato com a administração.</p></div></section>;
  if (state.status === "REQUESTING_LOCATION" || state.status === "CHECKING_LOCATION") return <section className="point-terminal"><div className="point-terminal-center"><LoaderCircle className="spin" /><strong>{state.status === "REQUESTING_LOCATION" ? "Obtendo localização…" : "Validando localização…"}</strong><p>A localização é coletada somente para validar este registro.</p></div></section>;
  if (state.status === "LOCATION_REJECTED") return <section className="point-terminal"><div className="point-terminal-center error"><ShieldAlert size={42} /><strong>Localização não autorizada</strong><p>{state.error}</p><button className="point-terminal-primary" onClick={() => dispatch({ type: "RESET" })}>Tentar novamente</button></div></section>;
  if ((state.status === "WAITING_FOR_FACE" || state.status === "CHECKING_FACE") && state.locationValidationId) return <TerminalFaceCapture locationValidationId={state.locationValidationId} onCapture={() => dispatch({ type: "FACE_CAPTURED" })} onApproved={(result) => { dispatch({ type: "BIOMETRIC_APPROVED", employee: { id: result.employeeId, displayName: result.displayName }, biometricValidationId: result.biometricValidationId, attemptId: result.attemptId }); window.setTimeout(() => dispatch({ type: "VALIDATED" }), 0); }} onRejected={(message) => dispatch({ type: "BIOMETRIC_REJECTED", message })} />;
  if (state.status === "IDENTIFICATION_FAILED") return <section className="point-terminal"><div className="point-terminal-center error"><ScanFace size={42} /><strong>Identificação não concluída</strong><p>{state.error}</p><button className="point-terminal-primary" onClick={() => dispatch({ type: "RESET" })}>Tentar novamente</button></div></section>;
  return <section className="point-terminal"><header><div><p>{collectorName}</p><h1>Terminal de ponto</h1></div><span className={`terminal-connection ${online ? "online" : "offline"}`}>{online ? "Online" : <><CloudOff size={15} /> Sem conexão</>}</span></header>{state.status === "IDLE" && <><div className="point-terminal-intro"><SynchronizedClock /></div><button className="point-terminal-primary" onClick={() => dispatch({ type: "START" })}>Iniciar registro</button></>}{state.status === "IDENTIFYING" && <div className="point-terminal-center"><strong>Identifique-se</strong>{developmentEmployees.length > 0 ? <select aria-label="Funcionário de teste" defaultValue="" onChange={(event) => { const employee = developmentEmployees.find((item) => item.id === event.target.value); if (employee) identify(employee); }}><option value="" disabled>Selecionar funcionário de teste</option>{developmentEmployees.map((employee) => <option value={employee.id} key={employee.id}>{employee.displayName}</option>)}</select> : <p>A identificação facial será disponibilizada em breve.</p>}</div>}{state.status === "READY" && <div className="point-terminal-center"><strong>{state.employee?.displayName}</strong><p>{state.employee?.jobTitle}</p><div className="terminal-actions"><button onClick={() => register("CLOCK_IN")}>Registrar entrada</button><button onClick={() => register("CLOCK_OUT")}>Registrar saída</button></div></div>}{state.status === "REGISTERING" && <div className="point-terminal-center"><LoaderCircle className="spin" /><strong>Registrando…</strong></div>}{state.status === "SUCCESS" && <div className="point-terminal-center success"><CheckCircle2 size={48} /><strong>Ponto registrado</strong><p>{state.employee?.displayName}</p><b>{state.result?.eventLabel}</b><time>{state.result && new Intl.DateTimeFormat("pt-BR", { timeStyle: "medium" }).format(new Date(state.result.recordedAt))}</time><small>NSR: {state.result?.nsr}</small></div>}{state.status === "ERROR" && <div className="point-terminal-center error"><strong>Registro não concluído</strong><p>{state.error}</p><button className="point-terminal-primary" onClick={() => dispatch({ type: "RESET" })}>Tentar novamente</button></div>}</section>;
}
