"use client";

import { useEffect, useReducer, useRef, useState } from "react";
import { CheckCircle2, CloudOff, LoaderCircle, ScanFace, ShieldAlert } from "lucide-react";
import { initialTerminalFlowState, terminalFlowReducer } from "@/terminal/flow-machine";
import type { IdentifiedEmployee } from "@/terminal/identification";
import { pendingRegistrations, queuePendingRegistration, terminalInstanceId, updatePendingRegistration, type PendingRegistration } from "@/terminal/offline-queue";
import { SynchronizedClock } from "./synchronized-clock";
import { TerminalFaceCapture } from "./terminal-face-capture";
import { TerminalContingencyForm } from "./terminal-contingency-form";

export function TerminalApp({ developmentEmployees = [] }: { developmentEmployees?: IdentifiedEmployee[] }) { const [state, dispatch] = useReducer(terminalFlowReducer, initialTerminalFlowState); const [online, setOnline] = useState(true); const [pendingCount, setPendingCount] = useState(0); const [authorized, setAuthorized] = useState<boolean | null>(null); const [blocked, setBlocked] = useState(false); const [collectorName, setCollectorName] = useState<string>(); const [code, setCode] = useState(""); const requestId = useRef("");
  const submitting = useRef(false);
  const clockEvidence = useRef<{ lastServerTime?: string; lastClockSyncAt?: string; clockOffsetMs?: number }>({});
  const offlineStartedAt = useRef<string | undefined>(undefined);
  async function heartbeat() { try { const pending = await pendingRegistrations(); const response = await fetch("/api/rep-p/collectors/heartbeat", { method: "POST", cache: "no-store", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ appVersion: "1.0.0", instanceId: terminalInstanceId(), pendingOperationCount: pending.length, offlineSince: offlineStartedAt.current ?? null, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }); setOnline(true); const data = await response.json(); setAuthorized(response.ok); setBlocked(data.status === "BLOCKED"); if (response.ok) setCollectorName(data.collector.name); } catch { setOnline(false); } }
  useEffect(() => { const initial = window.setTimeout(heartbeat, 0); const timer = window.setInterval(heartbeat, 30_000); const onOnline = () => { offlineStartedAt.current = undefined; heartbeat(); }; const onOffline = () => { offlineStartedAt.current ??= new Date().toISOString(); setOnline(false); }; window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); return () => { window.clearTimeout(initial); window.clearInterval(timer); window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, []);
  useEffect(() => { async function syncClock() { const started = Date.now(); try { const response = await fetch("/api/time", { cache: "no-store" }); const data = await response.json(); const midpoint = started + (Date.now() - started) / 2; clockEvidence.current = { lastServerTime: data.serverTime, lastClockSyncAt: new Date().toISOString(), clockOffsetMs: data.epochMs - midpoint }; } catch { offlineStartedAt.current ??= new Date().toISOString(); } } const initial = window.setTimeout(syncClock, 0); const timer = window.setInterval(syncClock, 60_000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, []);
  useEffect(() => { async function synchronize() { const pending = await pendingRegistrations(); setPendingCount(pending.length); for (const item of pending) { if (item.nextRetryAt && new Date(item.nextRetryAt) > new Date()) continue; try { await updatePendingRegistration(item, "SYNCING", item.result); const response = await fetch("/api/rep-p/terminal/entries", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": item.idempotencyKey }, body: JSON.stringify({ eventType: item.eventType, locationValidationId: item.locationValidationId, biometricValidationId: item.biometricValidationId, attemptId: item.attemptId, contingencyTicket: item.contingencyTicket, capturedAt: item.capturedAtDevice, operationId: item.operationId, clockEvidence: { lastServerTime: item.lastServerTime, lastClockSyncAt: item.lastClockSyncAt, clockOffsetMs: item.clockOffsetMs, offlineStartedAt: item.offlineStartedAt } }) }); const data = await response.json(); await updatePendingRegistration(item, response.ok ? "ACCEPTED" : response.status === 409 ? "REQUIRES_REVIEW" : "REJECTED", response.ok ? { nsr: data.nsr } : { error: data.error }); } catch { await updatePendingRegistration(item, "PENDING", { error: "Servidor indisponível" }); break; } } setPendingCount((await pendingRegistrations()).length); } const initial = window.setTimeout(synchronize, 0); window.addEventListener("online", synchronize); return () => { window.clearTimeout(initial); window.removeEventListener("online", synchronize); }; }, []);
  useEffect(() => { if (!state.employee) return; const timer = window.setTimeout(() => dispatch({ type: "RESET" }), state.status === "SUCCESS" ? 5_000 : 30_000); return () => window.clearTimeout(timer); }, [state.employee, state.status]);
  useEffect(() => { document.title = pendingCount ? `(${pendingCount}) Operações pendentes · UpTime` : "UpTime"; }, [pendingCount]);
  async function activate(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/rep-p/collectors/activate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); if (response.ok) await heartbeat(); }
  function identify(employee: IdentifiedEmployee) { dispatch({ type: "IDENTIFIED", employee }); window.setTimeout(() => dispatch({ type: "VALIDATED" }), 0); }
  async function requestLocation() { if (!("geolocation" in navigator)) { dispatch({ type: "LOCATION_REJECTED", message: "Localização indisponível neste dispositivo." }); return; } navigator.geolocation.getCurrentPosition(async (position) => { dispatch({ type: "LOCATION_CAPTURED" }); try { const response = await fetch("/api/rep-p/terminal/location", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: position.coords.accuracy, capturedAt: new Date(position.timestamp).toISOString(), source: "DEVICE_GEOLOCATION" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.status === "OUTSIDE_GEOFENCE" ? "Este terminal está fora da área permitida." : data.status === "LOW_ACCURACY" ? "A localização obtida não possui precisão suficiente." : "Não foi possível validar a localização."); dispatch({ type: "LOCATION_VALID", validationId: data.id }); } catch (error) { dispatch({ type: "LOCATION_REJECTED", message: error instanceof Error ? error.message : "Localização indisponível." }); } }, (error) => dispatch({ type: "LOCATION_REJECTED", message: error.code === error.PERMISSION_DENIED ? "A permissão de localização é necessária para registrar o ponto." : error.code === error.TIMEOUT ? "O tempo para obter a localização expirou." : "Localização indisponível." }), { enableHighAccuracy: true, timeout: 15_000, maximumAge: 0 }); }
  useEffect(() => { if (state.status !== "REQUESTING_LOCATION") return; const timer = window.setTimeout(requestLocation, 0); return () => window.clearTimeout(timer); }, [state.status]);
  async function register(eventType: "CLOCK_IN" | "CLOCK_OUT") { if (!state.employee || !state.locationValidationId || !state.biometricValidationId || !state.attemptId || !state.contingencyTicket || state.status !== "READY" || submitting.current) return; submitting.current = true; dispatch({ type: "REGISTER" }); requestId.current ||= crypto.randomUUID(); const capturedAtDevice = new Date().toISOString(); const pending: Omit<PendingRegistration, "status" | "retryCount"> = { operationId: crypto.randomUUID(), eventType, locationValidationId: state.locationValidationId, biometricValidationId: state.biometricValidationId, attemptId: state.attemptId, contingencyTicket: state.contingencyTicket, capturedAtDevice, offlineStartedAt: offlineStartedAt.current ?? capturedAtDevice, idempotencyKey: requestId.current, ...clockEvidence.current }; try { const response = await fetch("/api/rep-p/terminal/entries", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestId.current }, body: JSON.stringify({ eventType, locationValidationId: pending.locationValidationId, biometricValidationId: pending.biometricValidationId, attemptId: pending.attemptId, contingencyTicket: pending.contingencyTicket, capturedAt: capturedAtDevice, operationId: pending.operationId, clockEvidence: pending }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível registrar o ponto."); dispatch({ type: "SUCCEEDED", result: { eventLabel: eventType === "CLOCK_IN" ? "Entrada registrada" : "Saída registrada", recordedAt: data.recordedAt, nsr: data.nsr } }); } catch (error) { if (!navigator.onLine || error instanceof TypeError) { await queuePendingRegistration(pending); setPendingCount((await pendingRegistrations()).length); dispatch({ type: "FAILED", message: "Marcação protegida na fila do terminal. Ela será enviada automaticamente quando a conexão voltar." }); } else dispatch({ type: "FAILED", message: error instanceof Error ? error.message : "Servidor indisponível." }); } finally { requestId.current = ""; submitting.current = false; } }
  if (authorized === null) return <section className="point-terminal"><div className="point-terminal-center"><LoaderCircle className="spin" /><strong>Conectando ao terminal…</strong></div></section>;
  if (!authorized) return <section className="point-terminal"><header><ShieldAlert /><div><p>UpTime</p><h1>Ativar terminal</h1></div></header><form className="point-terminal-activation" onSubmit={activate}><label htmlFor="activation-code">Código de ativação</label><input id="activation-code" inputMode="numeric" maxLength={6} pattern="[0-9]{6}" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} /><button className="point-terminal-primary" disabled={code.length !== 6}>Ativar dispositivo</button></form></section>;
  if (blocked) return <section className="point-terminal"><div className="point-terminal-center"><ShieldAlert size={42} /><strong>Terminal indisponível</strong><p>Entre em contato com a administração.</p></div></section>;
  if (state.status === "REQUESTING_LOCATION" || state.status === "CHECKING_LOCATION") return <section className="point-terminal"><div className="point-terminal-center"><LoaderCircle className="spin" /><strong>{state.status === "REQUESTING_LOCATION" ? "Obtendo localização…" : "Validando localização…"}</strong><p>A localização é coletada somente para validar este registro.</p></div></section>;
  if (state.status === "LOCATION_REJECTED") return <section className="point-terminal"><div className="point-terminal-center error"><ShieldAlert size={42} /><strong>Localização não autorizada</strong><p>{state.error}</p><button className="point-terminal-primary" onClick={() => dispatch({ type: "RESET" })}>Tentar novamente</button>{!state.error?.includes("fora da área") && <TerminalContingencyForm failureType={state.error?.includes("precisão") ? "LOCATION_LOW_ACCURACY" : state.error?.includes("permissão") ? "LOCATION_PERMISSION_DENIED" : "LOCATION_UNAVAILABLE"} />}</div></section>;
  if ((state.status === "WAITING_FOR_FACE" || state.status === "CHECKING_FACE") && state.locationValidationId) return <TerminalFaceCapture locationValidationId={state.locationValidationId} onCapture={() => dispatch({ type: "FACE_CAPTURED" })} onApproved={(result) => { dispatch({ type: "BIOMETRIC_APPROVED", employee: { id: result.employeeId, displayName: result.displayName }, biometricValidationId: result.biometricValidationId, attemptId: result.attemptId, contingencyTicket: result.contingencyTicket }); window.setTimeout(() => dispatch({ type: "VALIDATED" }), 0); }} onRejected={(message, code) => dispatch({ type: "BIOMETRIC_REJECTED", message, code })} />;
  if (state.status === "IDENTIFICATION_FAILED") { const eligible = ["CAMERA_UNAVAILABLE", "BIOMETRIC_PROVIDER_UNAVAILABLE", "BIOMETRIC_ATTEMPTS_EXCEEDED"].includes(state.failureCode ?? ""); return <section className="point-terminal"><div className="point-terminal-center error"><ScanFace size={42} /><strong>Identificação não concluída</strong><p>{state.error}</p>{state.failureCode !== "BIOMETRIC_ATTEMPTS_EXCEEDED" && <button className="point-terminal-primary" onClick={() => dispatch({ type: "RETRY_FACE" })}>Tentar reconhecer novamente</button>}{eligible && <TerminalContingencyForm failureType={state.failureCode === "CAMERA_UNAVAILABLE" ? "CAMERA_UNAVAILABLE" : state.failureCode === "BIOMETRIC_ATTEMPTS_EXCEEDED" ? "BIOMETRIC_ATTEMPTS_EXCEEDED" : "BIOMETRIC_PROVIDER_UNAVAILABLE"} />}</div></section>; }
  return <section className="point-terminal"><header><div><p>{collectorName}</p><h1>Terminal de ponto</h1></div><span className={`terminal-connection ${online ? "online" : "offline"}`}>{online ? "Online" : <><CloudOff size={15} /> Sem conexão</>}</span></header>{state.status === "IDLE" && <><div className="point-terminal-intro"><SynchronizedClock /></div><button className="point-terminal-primary" onClick={() => dispatch({ type: "START" })}>Iniciar registro</button></>}{state.status === "IDENTIFYING" && <div className="point-terminal-center"><strong>Identifique-se</strong>{developmentEmployees.length > 0 ? <select aria-label="Funcionário de teste" defaultValue="" onChange={(event) => { const employee = developmentEmployees.find((item) => item.id === event.target.value); if (employee) identify(employee); }}><option value="" disabled>Selecionar funcionário de teste</option>{developmentEmployees.map((employee) => <option value={employee.id} key={employee.id}>{employee.displayName}</option>)}</select> : <p>A identificação facial será disponibilizada em breve.</p>}</div>}{state.status === "READY" && <div className="point-terminal-center"><strong>{state.employee?.displayName}</strong><p>{state.employee?.jobTitle}</p><div className="terminal-actions"><button onClick={() => register("CLOCK_IN")}>Registrar entrada</button><button onClick={() => register("CLOCK_OUT")}>Registrar saída</button></div></div>}{state.status === "REGISTERING" && <div className="point-terminal-center"><LoaderCircle className="spin" /><strong>Registrando…</strong></div>}{state.status === "SUCCESS" && <div className="point-terminal-center success"><CheckCircle2 size={48} /><strong>Ponto registrado</strong><p>{state.employee?.displayName}</p><b>{state.result?.eventLabel}</b><time>{state.result && new Intl.DateTimeFormat("pt-BR", { timeStyle: "medium" }).format(new Date(state.result.recordedAt))}</time><small>NSR: {state.result?.nsr}</small></div>}{state.status === "ERROR" && <div className="point-terminal-center error"><strong>Registro não concluído</strong><p>{state.error}</p><button className="point-terminal-primary" onClick={() => dispatch({ type: "RESET" })}>Tentar novamente</button></div>}</section>;
}
