"use client";
import { Camera, LoaderCircle, ScanFace } from "lucide-react";
import { useEffect, useRef, useState } from "react";
type Approved = { attemptId: string; biometricValidationId: string; employeeId: string; displayName: string; contingencyTicket: string };
export function TerminalFaceCapture({ locationValidationId, onCapture, onApproved, onRejected }: { locationValidationId: string; onCapture: () => void; onApproved: (result: Approved) => void; onRejected: (message: string, code?: string) => void }) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | undefined>(undefined); const [ready, setReady] = useState(false); const [checking, setChecking] = useState(false);
  useEffect(() => { let active = true; navigator.mediaDevices?.getUserMedia({ video: { facingMode: "user", width: { ideal: 640 }, height: { ideal: 480 } }, audio: false }).then((media) => { if (!active) { media.getTracks().forEach((track) => track.stop()); return; } stream.current = media; if (video.current) video.current.srcObject = media; setReady(true); }).catch(() => onRejected("Não foi possível acessar a câmera.", "CAMERA_UNAVAILABLE")); return () => { active = false; stream.current?.getTracks().forEach((track) => track.stop()); }; }, [onRejected]);
  async function analyze() { const element = video.current; if (!element || checking) return; setChecking(true); onCapture(); const canvas = document.createElement("canvas"); canvas.width = 640; canvas.height = 480; canvas.getContext("2d")?.drawImage(element, 0, 0, 640, 480); try { const response = await fetch("/api/rep-p/terminal/biometrics/identify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ locationValidationId, imageBase64: canvas.toDataURL("image/jpeg", .82) }) }); const data = response.headers.get("content-type")?.includes("application/json") ? await response.json() : { error: await response.text() }; if (!response.ok) { onRejected(data.error ?? "Não foi possível reconhecer o rosto.", data.code ?? (response.status === 429 ? "BIOMETRIC_ATTEMPTS_EXCEEDED" : undefined)); return; } stream.current?.getTracks().forEach((track) => track.stop()); onApproved(data); } catch { onRejected("Serviço biométrico temporariamente indisponível.", "BIOMETRIC_PROVIDER_UNAVAILABLE"); } }
  return <section className="point-terminal"><header><ScanFace /><div><p>Identificação biométrica</p><h1>Posicione seu rosto</h1></div></header><div className="terminal-face-camera"><video ref={video} autoPlay muted playsInline />{checking && <span><LoaderCircle className="spin" /> Verificando identidade…</span>}</div><p className="terminal-face-guidance">Permaneça sozinho diante da câmera e mantenha o rosto centralizado.</p><button className="point-terminal-primary" disabled={!ready || checking} onClick={analyze}><Camera size={18} /> {checking ? "Analisando…" : "Verificar identidade"}</button></section>;
}
