import { ArrowDownRight, ArrowUpRight, Calculator, History, RefreshCw, Scale, Settings2 } from "lucide-react";
import { createManualTimeBankAdjustmentAction, createTimeBankPolicyAction, processTimeBankAction } from "@/actions/time-bank";
import { getTimeBankAccumulatedBalance, listTimeBankEmployees, listTimeBankEntries, listTimeBankPolicies } from "@/services/time-bank.service";

function text(value: string | string[] | undefined) { return typeof value === "string" ? value : undefined; }
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Belem" }).format(new Date()); }
function monthStart(date: string) { return `${date.slice(0, 7)}-01`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function formatMinutes(value: number) { const sign = value > 0 ? "+" : value < 0 ? "−" : ""; const absolute = Math.abs(value); const hours = Math.floor(absolute / 60); const minutes = absolute % 60; return hours ? `${sign}${hours}h ${String(minutes).padStart(2, "0")}min` : `${sign}${minutes} min`; }
const typeLabels = { DAILY_CALCULATION: "Apuração diária", RECALCULATION: "Recálculo", MANUAL_ADJUSTMENT: "Ajuste manual" } as const;

export default async function TimeBankPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const current = today(); const employeeId = text(query.employeeId); const startDate = text(query.startDate) ?? monthStart(current); const endDate = text(query.endDate) ?? current;
  const [entries, employees, policies, accumulated] = await Promise.all([listTimeBankEntries({ employeeId, startDate, endDate }), listTimeBankEmployees(), listTimeBankPolicies(), getTimeBankAccumulatedBalance(employeeId)]);
  const credits = entries.filter((item) => item.amountMinutes > 0).reduce((sum, item) => sum + item.amountMinutes, 0); const debits = entries.filter((item) => item.amountMinutes < 0).reduce((sum, item) => sum + item.amountMinutes, 0); const balance = credits + debits;
  return <main className="dashboard-page time-bank-page"><div className="page-heading employees-heading"><div><p className="eyebrow">Controle reproduzível</p><h1>Banco de horas</h1><p>Processe apurações e acompanhe cada crédito ou débito em um extrato imutável.</p></div></div>
    {query.processed !== undefined ? <p className="success-message">Processamento concluído: {query.processed} novo(s), {query.unchanged ?? 0} sem alteração e {query.pending ?? 0} pendente(s).</p> : null}{query.saved === "adjustment" ? <p className="success-message">Ajuste manual registrado com sucesso.</p> : null}{query.saved === "policy" ? <p className="success-message">Nova política registrada. O histórico anterior foi preservado.</p> : null}{query.error ? <p className="form-error">Não foi possível concluir a operação. Revise os campos e tente novamente.</p> : null}
    <section className="time-bank-summary"><article><ArrowUpRight size={20} /><span><small>Créditos no período</small><strong>{formatMinutes(credits)}</strong></span></article><article><ArrowDownRight size={20} /><span><small>Débitos no período</small><strong>{formatMinutes(debits)}</strong></span></article><article className={balance < 0 ? "negative" : ""}><Scale size={20} /><span><small>Saldo no período</small><strong>{formatMinutes(balance)}</strong></span></article><article className={accumulated < 0 ? "negative" : ""}><History size={20} /><span><small>Saldo acumulado</small><strong>{formatMinutes(accumulated)}</strong></span></article></section>
    <div className="time-bank-layout"><section className="data-panel time-bank-ledger"><header><div><h2>Extrato</h2><p>O acumulado é a soma dos lançamentos exibidos.</p></div><span>{entries.length}</span></header><form className="time-bank-filters"><select name="employeeId" defaultValue={employeeId ?? ""}><option value="">Todos os funcionários</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName}</option>)}</select><input name="startDate" type="date" defaultValue={startDate} /><input name="endDate" type="date" defaultValue={endDate} /><button type="submit">Consultar</button></form>{entries.length ? <div className="time-bank-entries">{entries.map((entry) => <article key={entry.id}><span className={entry.amountMinutes < 0 ? "debit" : "credit"}>{entry.amountMinutes < 0 ? <ArrowDownRight size={18} /> : <ArrowUpRight size={18} />}</span><div><strong>{entry.employeeName}</strong><small>{entry.registrationNumber} · {formatDate(entry.referenceDate)}</small></div><div><strong>{typeLabels[entry.type]}</strong><small>{entry.reason}</small></div><em className={entry.amountMinutes < 0 ? "negative" : "positive"}>{formatMinutes(entry.amountMinutes)}</em><small>{entry.createdByName}</small></article>)}</div> : <div className="empty-state"><History size={30} /><h2>Nenhum lançamento</h2><p>Processe um período ou registre um ajuste autorizado.</p></div>}</section>
      <aside className="time-bank-tools"><section className="data-panel"><header><RefreshCw size={18} /><div><h2>Processar período</h2><p>Somente dias completos entram no extrato.</p></div></header><form action={processTimeBankAction}><label>Funcionário<select name="employeeId" defaultValue={employeeId ?? ""} required><option value="" disabled>Selecione</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName}</option>)}</select></label><label>Início<input name="startDate" type="date" defaultValue={startDate} required /></label><label>Fim<input name="endDate" type="date" defaultValue={endDate} required /></label><button><Calculator size={16} /> Processar e reconciliar</button></form></section><section className="data-panel"><header><Scale size={18} /><div><h2>Ajuste manual</h2><p>Use minutos positivos ou negativos.</p></div></header><form action={createManualTimeBankAdjustmentAction}><label>Funcionário<select name="employeeId" defaultValue={employeeId ?? ""} required><option value="" disabled>Selecione</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName}</option>)}</select></label><label>Data<input name="date" type="date" defaultValue={current} required /></label><label>Minutos<input name="amountMinutes" type="number" min="-14400" max="14400" placeholder="Ex.: 60 ou -30" required /></label><label>Motivo<textarea name="reason" rows={3} minLength={5} maxLength={500} required /></label><button><Scale size={16} /> Registrar ajuste</button></form></section></aside></div>
    <section className="data-panel time-bank-policies"><header><Settings2 size={18} /><div><h2>Políticas de conversão</h2><p>Novas vigências não reescrevem lançamentos anteriores.</p></div></header><div><form action={createTimeBankPolicyAction}><input name="name" placeholder="Nome da política" minLength={3} required /><label>Vigência<input name="effectiveFrom" type="date" required /></label><label>Crédito %<input name="creditPercent" type="number" min="0" max="300" defaultValue="100" required /></label><label>Débito %<input name="debitPercent" type="number" min="0" max="300" defaultValue="100" required /></label><button><Settings2 size={16} /> Criar política</button></form><div className="policy-list">{policies.length ? policies.map((policy) => <article key={policy.id}><strong>{policy.name}</strong><small>Desde {formatDate(policy.effectiveFrom)}</small><span>Crédito {policy.creditBasisPoints / 100}% · Débito {policy.debitBasisPoints / 100}%</span></article>) : <p>Política padrão ativa: crédito e débito em 100%.</p>}</div></div></section>
  </main>;
}
