import { CalendarCheck2, CalendarDays, CalendarRange, ChevronRight, Clock3, Plus, UsersRound } from "lucide-react";
import Link from "next/link";
import { listWorkSchedules } from "@/services/work-schedule.service";
import { formatDate } from "@/utils/format";

export default async function SchedulesPage() {
  const schedules = await listWorkSchedules();
  const employees = new Set(schedules.map((schedule) => schedule.employeeId)).size;
  const ongoing = schedules.filter((schedule) => !schedule.validTo).length;
  return <main className="dashboard-page schedules-page"><header className="schedules-heading"><div><p className="eyebrow">Planejamento da equipe</p><h1>Jornadas de trabalho</h1><p>Organize horários, folgas e períodos de vigência em um só lugar.</p></div><Link className="primary-button action-button" href="/admin/jornadas/nova"><Plus size={18} /> Nova jornada</Link></header><section className="schedule-stats" aria-label="Resumo das jornadas"><article><span><CalendarCheck2 size={20} /></span><div><strong>{schedules.length}</strong><small>Jornadas cadastradas</small></div></article><article><span><UsersRound size={20} /></span><div><strong>{employees}</strong><small>Funcionários com escala</small></div></article><article><span><Clock3 size={20} /></span><div><strong>{ongoing}</strong><small>Sem data final</small></div></article></section><section className="schedules-panel"><header><div><h2>Escalas cadastradas</h2><p>Abra uma jornada para consultar ou editar seus horários.</p></div><span className="schedule-count">{schedules.length}</span></header>{schedules.length ? <div className="schedules-cards">{schedules.map((schedule) => <Link href={`/admin/jornadas/${schedule.id}`} className="schedule-card" key={schedule.id}><span className="schedule-card-icon"><CalendarRange size={20} /></span><span className="schedule-card-person"><small>Funcionário</small><strong>{schedule.employeeName}</strong><em>{schedule.position}</em></span><span className="schedule-card-validity"><small>Jornada e vigência</small><strong>{schedule.name}</strong><em>{formatDate(schedule.validFrom)} — {schedule.validTo ? formatDate(schedule.validTo) : "sem data final"}</em></span><ChevronRight className="schedule-card-arrow" size={19} /></Link>)}</div> : <div className="empty-state"><CalendarDays size={30} /><h2>Nenhuma jornada cadastrada</h2><p>Crie a primeira jornada semanal da equipe.</p><Link href="/admin/jornadas/nova">Cadastrar jornada</Link></div>}</section></main>;
}
