export type PendingStatus = "PENDING" | "SYNCING" | "ACCEPTED" | "REJECTED" | "REQUIRES_REVIEW";
export type PendingRegistration = { operationId: string; idempotencyKey: string; eventType: "CLOCK_IN" | "CLOCK_OUT"; locationValidationId: string; biometricValidationId: string; attemptId: string; contingencyTicket: string; capturedAtDevice: string; offlineStartedAt: string; lastServerTime?: string; lastClockSyncAt?: string; clockOffsetMs?: number; status: PendingStatus; retryCount: number; nextRetryAt?: string; result?: { nsr?: string; error?: string } };
export interface PendingStore { list(): Promise<PendingRegistration[]>; put(item: PendingRegistration): Promise<void>; }
const DB_NAME = "uptime-terminal"; const STORE_NAME = "pending-point-operations";
function database(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(STORE_NAME)) request.result.createObjectStore(STORE_NAME, { keyPath: "operationId" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
export const indexedDbPendingStore: PendingStore = { async list() { const db = await database(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, "readonly").objectStore(STORE_NAME).getAll(); request.onsuccess = () => resolve(request.result as PendingRegistration[]); request.onerror = () => reject(request.error); }); }, async put(item) { const db = await database(); return new Promise((resolve, reject) => { const transaction = db.transaction(STORE_NAME, "readwrite"); transaction.objectStore(STORE_NAME).put(item); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); }); } };
export function retryDelayMs(retryCount: number) { return [1_000, 2_000, 5_000, 10_000, 30_000][Math.min(retryCount, 4)]; }
export async function queuePendingRegistration(item: Omit<PendingRegistration, "status" | "retryCount">, store = indexedDbPendingStore) { const current = await store.list(); if (!current.some((entry) => entry.operationId === item.operationId)) await store.put({ ...item, status: "PENDING", retryCount: 0 }); }
export async function pendingRegistrations(store = indexedDbPendingStore) { return (await store.list()).filter((item) => item.status === "PENDING" || item.status === "SYNCING").sort((a, b) => a.capturedAtDevice.localeCompare(b.capturedAtDevice)); }
export async function updatePendingRegistration(item: PendingRegistration, status: PendingStatus, result: PendingRegistration["result"], store = indexedDbPendingStore) { const retryCount = status === "PENDING" ? item.retryCount + 1 : item.retryCount; await store.put({ ...item, status, retryCount, result, nextRetryAt: status === "PENDING" ? new Date(Date.now() + retryDelayMs(retryCount)).toISOString() : undefined }); }
