import { ClipboardCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { requireManagerPortal } from "@/auth/session";
import { db } from "@/db";
import { employees } from "@/db/schema";
import { inArray } from "drizzle-orm";
import { listManagerRequests, managedEmployeeIds } from "@/services/portal.service";

export default async function ManagerPage() { const session = await requireManagerPortal(); const ids = await managedEmployeeIds(session.user.id); const [team, requests] = await Promise.all([ids.length ? db.select({ id: employees.id, fullName: employees.fullName, position: employees.position, registrationNumber: employees.registrationNumber }).from(employees).where(inArray(employees.id, ids)) : [], listManagerRequests(session.user.id)]); return <main className="portal-page"><section className="portal-welcome"><div><p>Área do gestor</p><h1>Equipe sob sua responsabilidade</h1><span>Seu acesso é limitado aos funcionários expressamente vinculados.</span></div><Link className="primary-button" href="/gestao/solicitacoes">Analisar solicitações</Link></section><section className="portal-metrics"><article><span><UsersRound /></span><div><small>Funcionários no escopo</small><strong>{team.length}</strong></div></article><article><span><ClipboardCheck /></span><div><small>Solicitações pendentes</small><strong>{requests.filter((item) => item.status === "PENDING").length}</strong></div></article></section><section className="portal-card"><header><div><h2>Minha equipe</h2><p>Somente os vínculos autorizados pelo administrador.</p></div></header><div className="portal-list">{team.map((employee) => <article key={employee.id}><div><strong>{employee.fullName}</strong><small>{employee.position} · {employee.registrationNumber}</small></div></article>)}{!team.length ? <p className="portal-empty">Nenhum funcionário foi atribuído a este gestor.</p> : null}</div></section></main>; }
