import { describe, expect, it } from "vitest";
import { runPontoSyncCycle } from "./agent";
import type { PontoSyncState } from "./types";

const record = { nsr: "42", employeeRegistration: "M1", occurredAt: "2026-08-14T08:00:00-03:00", eventType: "CLOCK" as const };
function memoryStore(initial: PontoSyncState = { version: 1, queue: [] }) { let state = structuredClone(initial); return { read: async () => structuredClone(state), write: async (next: PontoSyncState) => { state = structuredClone(next); }, inspect: () => state }; }

describe("Ponto Sync agent", () => {
  it("confirma o NSR somente depois da API aceitar o lote", async () => { const store = memoryStore(); const result = await runPontoSyncCycle({ adapter: { id: "TEST", fetchAfter: async () => [record] }, client: { send: async () => ({ status: "PROCESSED", received: 1, inserted: 1, duplicates: 0, rejected: 0 }) }, store, batchSize: 100 }); expect(result.status).toBe("confirmed"); expect(store.inspect().lastConfirmedNsr).toBe("42"); expect(store.inspect().queue).toHaveLength(0); });
  it("mantém lote, request id e NSR após falha para retomar sem perda", async () => { const now = new Date("2026-08-14T12:00:00Z"); const store = memoryStore(); await runPontoSyncCycle({ adapter: { id: "TEST", fetchAfter: async () => [record] }, client: { send: async () => { throw new Error("offline"); } }, store, batchSize: 100, now: () => now, random: () => 0.5 }); const queued = store.inspect().queue[0]; expect(queued?.records).toEqual([record]); expect(queued?.attempts).toBe(1); expect(store.inspect().lastConfirmedNsr).toBeUndefined(); expect(queued?.nextAttemptAt).toBe("2026-08-14T12:00:01.000Z"); });
  it("não consulta novamente a origem enquanto existe lote pendente", async () => { let calls = 0; const store = memoryStore({ version: 1, queue: [{ id: "batch", requestId: "request-fixed", records: [record], attempts: 1, nextAttemptAt: "2026-08-14T12:01:00Z", createdAt: "2026-08-14T12:00:00Z" }] }); await runPontoSyncCycle({ adapter: { id: "TEST", fetchAfter: async () => { calls++; return []; } }, client: { send: async () => { throw new Error("não deve enviar"); } }, store, batchSize: 100, now: () => new Date("2026-08-14T12:00:30Z") }); expect(calls).toBe(0); expect(store.inspect().queue[0]?.requestId).toBe("request-fixed"); });
  it("gera nova requisição para reprocessar rejeições sem descartar o lote", async () => { const store = memoryStore(); await runPontoSyncCycle({ adapter: { id: "TEST", fetchAfter: async () => [record] }, client: { send: async () => ({ status: "PARTIAL", received: 1, inserted: 0, duplicates: 0, rejected: 1 }) }, store, batchSize: 100, now: () => new Date("2026-08-14T12:00:00Z"), random: () => 0.5 }); expect(store.inspect().queue[0]?.records).toEqual([record]); expect(store.inspect().queue[0]?.requestId).toMatch(/^[0-9a-f-]{36}$/); expect(store.inspect().lastConfirmedNsr).toBeUndefined(); });
});
