import { AlertTriangle, Clock3, Download, FileSpreadsheet, FileText, Filter, Timer, UsersRound, WalletCards } from "lucide-react";
import Link from "next/link";
import { dailyStatusValues, reportStatusLabels } from "@/services/report-core";
import { generateOperationalReport, listReportEmployees } from "@/services/report.service";
import { reportFiltersSchema } from "@/validations/report";

function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Belem" }).format(new Date()); }
function monthStart(date: string) { return `${date.slice(0, 7)}-01`; }
function minutes(value: number) { const sign = value < 0 ? "−" : ""; const absolute = Math.abs(value); return `${sign}${Math.floor(absolute / 60)}h ${String(absolute % 60).padStart(2, "0")}min`; }
function date(value: string) { return new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function params(filters: { startDate: string; endDate: string; employeeId?: string; status?: string }) { const query = new URLSearchParams({ startDate: filters.startDate, endDate: filters.endDate }); if (filters.employeeId) query.set("employeeId", filters.employeeId); if (filters.status) query.set("status", filters.status); return query.toString(); }

export default async function ReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const current = today(); const candidate = { startDate: typeof query.startDate === "string" ? query.startDate : monthStart(current), endDate: typeof query.endDate === "string" ? query.endDate : current, employeeId: typeof query.employeeId === "string" && query.employeeId ? query.employeeId : undefined, status: typeof query.status === "string" && query.status ? query.status : undefined }; const parsed = reportFiltersSchema.safeParse(candidate); const employees = await listReportEmployees(); const report = parsed.success ? await generateOperationalReport(parsed.data) : undefined; const exportQuery = parsed.success ? params(parsed.data) : "";
  return <main className="dashboard-page reports-page">
    <div className="page-heading reports-heading"><div><p className="eyebrow">Informação gerencial</p><h1>Relatórios operacionais</h1><p>Analise presença, faltas, atrasos, adicionais e banco de horas usando os mesmos filtros das exportações.</p></div><span><FileText size={18} /> Espelho gerencial — não oficial</span></div>
    <section className="data-panel report-filter-panel"><header><Filter size={18} /><div><h2>Filtros do relatório</h2><p>Período máximo de 366 dias.</p></div></header><form><label>Data inicial<input name="startDate" type="date" defaultValue={candidate.startDate} required /></label><label>Data final<input name="endDate" type="date" defaultValue={candidate.endDate} required /></label><label>Funcionário<select name="employeeId" defaultValue={candidate.employeeId ?? ""}><option value="">Todos</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName} · {employee.registrationNumber}</option>)}</select></label><label>Situação<select name="status" defaultValue={candidate.status ?? ""}><option value="">Todas</option>{dailyStatusValues.map((status) => <option value={status} key={status}>{reportStatusLabels[status]}</option>)}</select></label><div className="report-filter-actions"><button type="submit">Gerar relatório</button><Link href="/admin/relatorios">Limpar filtros</Link></div></form></section>
    {!parsed.success ? <p className="report-error"><AlertTriangle size={17} /> Filtros inválidos. Confira as datas e o intervalo máximo permitido.</p> : null}
    {report ? <><section className="report-summary"><article><span><UsersRound size={19} /></span><div><small>Linhas encontradas</small><strong>{report.rows.length}</strong></div></article><article><span><Timer size={19} /></span><div><small>Horas trabalhadas</small><strong>{minutes(report.totals.workedMinutes)}</strong></div></article><article><span><Clock3 size={19} /></span><div><small>Atrasos</small><strong>{minutes(report.totals.lateMinutes)}</strong></div></article><article><span><WalletCards size={19} /></span><div><small>Banco no período</small><strong>{minutes(report.totals.timeBankMinutes)}</strong></div></article><article><span><AlertTriangle size={19} /></span><div><small>Faltas / pendências</small><strong>{report.totals.absences} / {report.totals.pending}</strong></div></article></section>
      <section className="report-export"><div><Download size={19} /><span><strong>Exportar resultado atual</strong><small>Os arquivos repetem exatamente estes filtros e totais.</small></span></div><div><a href={`/admin/relatorios/exportar/csv?${exportQuery}`}><FileSpreadsheet size={17} /> CSV</a><a href={`/admin/relatorios/exportar/pdf?${exportQuery}`}><FileText size={17} /> PDF</a></div></section>
      <section className="data-panel report-results"><header><div><h2>Espelho gerencial de ponto</h2><p>{date(report.filters.startDate)} — {date(report.filters.endDate)} · documento operacional não oficial</p></div><span>{report.rows.length}</span></header>{report.rows.length ? <div className="report-table"><div className="report-table-head"><span>Data e funcionário</span><span>Situação</span><span>Jornada e marcações</span><span>Totais do dia</span></div>{report.rows.map((row) => <article key={`${row.employeeId}:${row.date}`}><div className="report-person"><strong>{date(row.date)} · {row.employeeName}</strong><small>{row.position} · {row.registrationNumber}</small></div><span className={`report-status status-${row.status.toLowerCase()}`}>{reportStatusLabels[row.status]}</span><div className="report-times"><strong>{row.schedule}</strong><small>{row.entries || "Sem marcações"}</small></div><div className="report-row-metrics"><span><small>Trabalhado</small><strong>{minutes(row.workedMinutes)}</strong></span><span><small>Atraso</small><strong>{minutes(row.lateMinutes)}</strong></span><span><small>Banco</small><strong>{minutes(row.timeBankMinutes)}</strong></span></div></article>)}</div> : <div className="empty-state"><FileText size={30} /><h2>Nenhum resultado</h2><p>Não existem registros correspondentes aos filtros informados.</p></div>}</section></> : null}
  </main>;
}
