import { Clock3, Filter, Plus } from "lucide-react";
import Link from "next/link";
import { listTimeEntries } from "@/services/time-entry.service";
import { listEligibleEmployees } from "@/services/work-schedule.service";

const sourceLabels = { SIMULATOR: "Simulador", IMPORT: "Importação", REP_C: "REP-C", REP_P: "REP-P" } as const;
function validDate(value: unknown) { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : undefined; }
function formatDateTime(value: Date) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Belem" }).format(value); }

export default async function TimeEntriesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams;
  const employeeId = typeof query.employeeId === "string" ? query.employeeId : undefined;
  const date = validDate(query.date);
  const source = query.source === "SIMULATOR" || query.source === "IMPORT" || query.source === "REP_C" ? query.source : undefined;
  const [entries, employees] = await Promise.all([listTimeEntries({ employeeId, source, start: date ? new Date(`${date}T00:00:00-03:00`) : undefined, end: date ? new Date(`${date}T23:59:59.999-03:00`) : undefined }), listEligibleEmployees()]);
  return <main className="dashboard-page time-entries-page"><div className="page-heading employees-heading"><div><p className="eyebrow">Registros originais</p><h1>Marcações de ponto</h1><p>Consulte os eventos recebidos sem alterar o conteúdo original.</p></div><Link className="primary-button action-button" href={`/admin/marcacoes/simular${employeeId ? `?employeeId=${employeeId}` : ""}`}><Plus size={18} /> Simular marcações</Link></div>{query.generated !== undefined ? <p className="success-message">{query.generated} marcações inseridas. {query.ignored ?? "0"} duplicadas foram ignoradas.</p> : null}<section className="data-panel time-entries-panel"><form className="time-entry-filters"><span><Filter size={17} /> Filtros</span><select name="employeeId" defaultValue={employeeId ?? ""}><option value="">Todos os funcionários</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName}</option>)}</select><input name="date" type="date" defaultValue={date} /><select name="source" defaultValue={source ?? ""}><option value="">Todas as origens</option>{Object.entries(sourceLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button type="submit">Aplicar</button></form><div className="table-summary"><strong>{entries.length}</strong> {entries.length === 1 ? "marcação encontrada" : "marcações encontradas"}</div>{entries.length ? <div className="time-entry-list">{entries.map((entry) => <article key={entry.id}><span className="time-entry-icon"><Clock3 size={18} /></span><div className="time-entry-person"><strong>{entry.employeeName}</strong><small>{entry.position} · {entry.registrationNumber}</small></div><div className="time-entry-moment"><small>Horário oficial</small><strong>{formatDateTime(entry.occurredAt)}</strong></div><span className={`time-entry-source source-${entry.source.toLowerCase()}`}>{sourceLabels[entry.source]}</span><div className="time-entry-origin"><small>Identificador externo</small><strong>{entry.externalId}</strong></div></article>)}</div> : <div className="empty-state"><Clock3 size={30} /><h2>Nenhuma marcação encontrada</h2><p>Ajuste os filtros ou gere registros simulados para desenvolvimento.</p></div>}</section><p className="immutable-note">Marcações originais são imutáveis. Correções futuras serão registradas separadamente, preservando o evento recebido.</p></main>;
}
