const BYTE_RANGE_PLACEHOLDER = "/ByteRange [0 0000000000 0000000000 0000000000]";
const CONTENT_HEX_LENGTH = 32768;
export const PADES_SIGNATURE_DICTIONARY = `<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached ${BYTE_RANGE_PLACEHOLDER} /Contents <${"0".repeat(CONTENT_HEX_LENGTH)}> >>`;

function locate(pdf: Uint8Array) { const text = Buffer.from(pdf).toString("latin1"); const rangeOffset = text.indexOf(BYTE_RANGE_PLACEHOLDER); const contentsMarker = text.indexOf("/Contents <", rangeOffset); if (rangeOffset < 0 || contentsMarker < 0) throw new Error("PADES_PLACEHOLDER_MISSING"); const contentsStart = contentsMarker + "/Contents ".length; const contentsEnd = contentsStart + CONTENT_HEX_LENGTH + 2; if (text[contentsStart] !== "<" || text[contentsEnd - 1] !== ">") throw new Error("PADES_PLACEHOLDER_INVALID"); return { text, rangeOffset, contentsStart, contentsEnd }; }
function padded(value: number) { const result = String(value).padStart(10, "0"); if (result.length !== 10) throw new Error("PADES_FILE_TOO_LARGE"); return result; }
export function preparePadesByteRange(pdf: Uint8Array) { const found = locate(pdf); const replacement = `/ByteRange [0 ${padded(found.contentsStart)} ${padded(found.contentsEnd)} ${padded(pdf.length - found.contentsEnd)}]`; if (replacement.length !== BYTE_RANGE_PLACEHOLDER.length) throw new Error("PADES_BYTE_RANGE_INVALID"); const prepared = Buffer.from(pdf); prepared.write(replacement, found.rangeOffset, "latin1"); return { prepared: new Uint8Array(prepared), signedContent: new Uint8Array(Buffer.concat([prepared.subarray(0, found.contentsStart), prepared.subarray(found.contentsEnd)])), contentsStart: found.contentsStart, contentsEnd: found.contentsEnd };
}
export function embedPadesSignature(prepared: Uint8Array, signature: Uint8Array, contentsStart: number, contentsEnd: number) { const hex = Buffer.from(signature).toString("hex").toUpperCase(); const available = contentsEnd - contentsStart - 2; if (hex.length > available) throw new Error("PADES_SIGNATURE_TOO_LARGE"); const output = Buffer.from(prepared); output.write(`<${hex.padEnd(available, "0")}>`, contentsStart, "latin1"); return new Uint8Array(output); }
function derLength(bytes: Uint8Array) { if (bytes[0] !== 0x30 || bytes.length < 2) throw new Error("SIGNATURE_MALFORMED"); const first = bytes[1]!; if (first < 0x80) return 2 + first; const count = first & 0x7f; if (!count || count > 4 || bytes.length < 2 + count) throw new Error("SIGNATURE_MALFORMED"); let length = 0; for (let index = 0; index < count; index += 1) length = length * 256 + bytes[2 + index]!; return 2 + count + length; }
export function extractPadesSignature(pdf: Uint8Array) { const text = Buffer.from(pdf).toString("latin1"); const match = text.match(/\/ByteRange \[0 (\d{10}) (\d{10}) (\d{10})\]/); if (!match) throw new Error("SIGNATURE_MALFORMED"); const contentsStart = Number(match[1]); const contentsEnd = Number(match[2]); const finalLength = Number(match[3]); if (contentsEnd + finalLength !== pdf.length || text[contentsStart] !== "<" || text[contentsEnd - 1] !== ">") throw new Error("SIGNATURE_MALFORMED"); const hex = text.slice(contentsStart + 1, contentsEnd - 1); const paddedSignature = new Uint8Array(Buffer.from(hex, "hex")); const length = derLength(paddedSignature); return { signature: paddedSignature.slice(0, length), signedContent: new Uint8Array(Buffer.concat([Buffer.from(pdf).subarray(0, contentsStart), Buffer.from(pdf).subarray(contentsEnd)])) };
}
