import { FileText, RefreshCcw, TimerReset } from "lucide-react";
import { createPortalCorrectionAction, createPortalSwapAction } from "@/actions/portal";
import { requireEmployeePortal } from "@/auth/session";
import { MedicalCertificateForm } from "@/components/medical-certificates/medical-certificate-form";
import { getEmployeePortalData } from "@/services/portal.service";

export default async function PortalRequestsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireEmployeePortal(); const data = await getEmployeePortalData(session.employeeId); const query = await searchParams;
  return <main className="portal-page"><div className="portal-title"><p>Autoatendimento</p><h1>Solicitações</h1><span>Envie informações para análise da gestão. Nada é alterado sem aprovação.</span></div>{query.saved ? <p className="portal-feedback success">Solicitação enviada com sucesso.</p> : null}{query.error ? <p className="portal-feedback error">Revise os campos e tente novamente.</p> : null}<div className="portal-request-grid"><section className="portal-card portal-form-card"><header><span><TimerReset /></span><div><h2>Correção de ponto</h2><p>Informe o dia e o que precisa ser corrigido.</p></div></header><form action={createPortalCorrectionAction} className="portal-form"><label>Data<input name="date" type="date" required /></label><label>Tipo<select name="type" required><option value="ADD_ENTRY">Adicionar marcação</option><option value="FORGOTTEN_EXIT">Saída esquecida</option><option value="OTHER">Outra correção</option></select></label><label>Horário pretendido<input name="requestedTime" type="time" /></label><label className="wide">Justificativa<textarea name="reason" minLength={5} maxLength={500} required /></label><button className="primary-button" type="submit">Enviar correção</button></form></section><section className="portal-card portal-form-card"><header><span><RefreshCcw /></span><div><h2>Troca de folga</h2><p>Proponha a data de folga e a data de trabalho.</p></div></header><form action={createPortalSwapAction} className="portal-form"><label>Data da folga<input name="dayOffDate" type="date" required /></label><label>Data para trabalhar<input name="workDate" type="date" required /></label><label className="wide">Justificativa<textarea name="reason" minLength={5} maxLength={500} required /></label><button className="primary-button" type="submit">Solicitar troca</button></form></section></div><section className="portal-card portal-certificate"><header><span><FileText /></span><div><h2>Enviar atestado</h2><p>O documento ficará pendente até ser analisado pela gestão.</p></div></header><MedicalCertificateForm portal employeeId={session.employeeId} employees={[]} /></section><section className="portal-card"><header><div><h2>Histórico de correções</h2><p>Acompanhe a situação de cada pedido.</p></div></header><div className="portal-list">{data.requests.map((item) => <article key={item.id}><div><strong>{item.date} · {item.type}</strong><small>{item.reason}</small></div><span className={`portal-status ${item.status.toLowerCase()}`}>{item.status}</span></article>)}{!data.requests.length ? <p className="portal-empty">Nenhuma correção solicitada.</p> : null}</div></section></main>;
}
