import { eq } from "drizzle-orm";
import { ArrowLeft, ScanFace, ShieldOff } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { enrollBiometricAction, revokeBiometricAction } from "@/actions/biometrics";
import { BiometricEnrollment } from "@/components/biometrics/biometric-enrollment";
import { db } from "@/db";
import { employeeBiometricProfiles, employees } from "@/db/schema";
import { requireBiometricPermission } from "@/modules/biometrics/services/biometric-permission.service";
export default async function EmployeeBiometricPage({ params }: { params: Promise<{ id: string }> }) { await requireBiometricPermission("BIOMETRIC_VIEW_STATUS"); const { id } = await params; const [employee] = await db.select({ id: employees.id, name: employees.fullName, profileId: employeeBiometricProfiles.id, status: employeeBiometricProfiles.status, enrolledAt: employeeBiometricProfiles.enrolledAt, algorithm: employeeBiometricProfiles.algorithmVersion }).from(employees).leftJoin(employeeBiometricProfiles, eq(employeeBiometricProfiles.employeeId, employees.id)).where(eq(employees.id, id)).limit(1); if (!employee) notFound(); return <main className="dashboard-page biometric-admin-page"><Link className="back-link" href={`/admin/funcionarios/${id}`}><ArrowLeft size={16} /> Voltar ao funcionário</Link><header className="page-heading"><div><p className="eyebrow">Funcionário</p><h1>Biometria facial</h1><p>{employee.name}</p></div></header><div className="biometric-admin-grid"><section className="data-panel biometric-status-card"><header><ScanFace /><div><h2>Status biométrico</h2><p>Nenhum template ou score é exibido nesta interface.</p></div></header><dl><div><dt>Status</dt><dd>{employee.status ?? "SEM CADASTRO"}</dd></div><div><dt>Cadastrada em</dt><dd>{employee.enrolledAt?.toLocaleDateString("pt-BR") ?? "—"}</dd></div><div><dt>Algoritmo</dt><dd>{employee.algorithm ?? "—"}</dd></div></dl>{employee.status === "ACTIVE" && <form action={revokeBiometricAction.bind(null, id)}><button className="danger-button" type="submit"><ShieldOff size={16} /> Revogar biometria</button></form>}</section><section className="data-panel biometric-capture-card"><header><div><h2>{employee.profileId ? "Refazer cadastro" : "Cadastrar biometria"}</h2><p>A imagem será descartada após a extração do template.</p></div></header><BiometricEnrollment action={enrollBiometricAction.bind(null, id)} /></section></div></main>; }
