import { ZodError } from "zod";
import { authenticateRepPCollector } from "@/services/rep-p-collector-auth.service";
import { registerRepPPoint } from "@/services/rep-p-registration.service";
import { consumeRateLimit, rateLimitResponse } from "@/services/rate-limit.service";
import { log } from "@/services/logger";
import { repPCollectorHeadersSchema, repPEntryRequestSchema } from "@/validations/rep-p";
import { RepPRegistrationError } from "@/rep-p/registration-core";

export const dynamic = "force-dynamic"; export const runtime = "nodejs";
export async function POST(request: Request) { if (!request.headers.get("content-type")?.toLowerCase().startsWith("application/json")) return Response.json({ error: "Content-Type deve ser application/json." }, { status: 415 }); const headers = repPCollectorHeadersSchema.safeParse({ collectorId: request.headers.get("x-rep-p-collector-id"), authorization: request.headers.get("authorization") }); if (!headers.success) return Response.json({ error: "Coletor não autorizado." }, { status: 401 }); const token = headers.data.authorization.replace(/^Bearer\s+/i, ""); let collector; try { collector = await authenticateRepPCollector(headers.data.collectorId, token); } catch (error) { log("error", "rep_p.collector_auth_configuration_failed", { error }); return Response.json({ error: "Registro indisponível." }, { status: 503 }); } if (!collector) return Response.json({ error: "Coletor não autorizado." }, { status: 401 }); const limited = await consumeRateLimit(request, "rep-p-entry", 30, 60, collector.id); if (!limited.allowed) return rateLimitResponse(limited); try { const text = await request.text(); if (Buffer.byteLength(text) > 16_384) return Response.json({ error: "Payload excede o limite." }, { status: 413 }); const input = repPEntryRequestSchema.parse(JSON.parse(text)); const result = await registerRepPPoint({ ...input, collectorId: collector.id }); return Response.json(result, { status: 201, headers: { "Cache-Control": "no-store" } }); } catch (error) { if (error instanceof SyntaxError || error instanceof ZodError) return Response.json({ error: "Solicitação inválida." }, { status: 400 }); if (error instanceof RepPRegistrationError) return Response.json({ error: error.message, code: error.code }, { status: 422 }); log("error", "rep_p.entry_failed", { collectorId: collector.id, error }); return Response.json({ error: "Falha ao registrar marcação." }, { status: 500 }); } }
