"use client";

import { CalendarCog, LoaderCircle, Save } from "lucide-react";
import Link from "next/link";
import { useActionState, useState } from "react";
import { saveScheduleExceptionAction, type ExceptionFormState } from "@/actions/schedule-exceptions";

export function ScheduleExceptionForm({ employees, employeeId, date }: { employees: Array<{ id: string; fullName: string; registrationNumber: string }>; employeeId?: string; date?: string }) {
  const [state, action, pending] = useActionState(saveScheduleExceptionAction, {} as ExceptionFormState);
  const [type, setType] = useState<"WORK" | "OFF">("OFF");
  return <form className="employee-form exception-form" action={action}>
    <section className="form-section"><div className="form-section-heading"><span><CalendarCog size={20} /></span><div><h2>Data e funcionário</h2><p>O ajuste substitui a jornada padrão somente nesta data.</p></div></div><div className="form-grid"><div className="field-group"><label htmlFor="employeeId">Funcionário *</label><select id="employeeId" name="employeeId" defaultValue={employeeId ?? ""} required><option value="" disabled>Selecione</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.fullName} · {employee.registrationNumber}</option>)}</select></div><div className="field-group"><label htmlFor="date">Data *</label><input id="date" name="date" type="date" defaultValue={date} required /></div></div></section>
    <section className="form-section"><div className="form-section-heading"><span><CalendarCog size={20} /></span><div><h2>Ajuste operacional</h2><p>Registre uma folga excepcional ou um horário especial de trabalho.</p></div></div><div className="exception-body"><fieldset className="exception-type"><legend>Situação *</legend><label className={type === "OFF" ? "selected" : ""}><input type="radio" name="type" value="OFF" checked={type === "OFF"} onChange={() => setType("OFF")} /><span><strong>Folga excepcional</strong><small>Não haverá trabalho previsto nesta data.</small></span></label><label className={type === "WORK" ? "selected" : ""}><input type="radio" name="type" value="WORK" checked={type === "WORK"} onChange={() => setType("WORK")} /><span><strong>Trabalho excepcional</strong><small>Use horários diferentes da jornada padrão.</small></span></label></fieldset>{type === "WORK" ? <div className="form-grid exception-times"><div className="field-group"><label>Entrada *</label><input name="startTime" type="time" required /></div><div className="field-group"><label>Saída *</label><input name="endTime" type="time" required /></div><div className="field-group"><label>Início do intervalo</label><input name="breakStartTime" type="time" /></div><div className="field-group"><label>Fim do intervalo</label><input name="breakEndTime" type="time" /></div><div className="field-group"><label>Tolerância (min)</label><input name="toleranceMinutes" type="number" min="0" max="120" defaultValue="10" /></div></div> : <input type="hidden" name="toleranceMinutes" value="0" />}<div className="field-group"><label htmlFor="reason">Motivo do ajuste *</label><textarea id="reason" name="reason" rows={4} maxLength={500} placeholder="Explique por que a escala deste dia será diferente." required /></div></div></section>
    {state.message ? <div className="form-error" role="alert"><strong>{state.message}</strong>{state.errors?.length ? <ul>{state.errors.map((error) => <li key={error}>{error}</li>)}</ul> : null}</div> : null}
    <div className="form-actions"><Link className="cancel-button" href="/admin/escalas">Cancelar</Link><button className="primary-button action-button" disabled={pending} type="submit">{pending ? <LoaderCircle className="spin" size={18} /> : <Save size={18} />}{pending ? "Salvando..." : "Salvar ajuste"}</button></div>
  </form>;
}
