import "server-only";
import { createHash, createHmac } from "node:crypto";
import { and, asc, desc, eq, inArray, isNull, lte, or } from "drizzle-orm";
import { db } from "@/db";
import { employees, establishments, legalSettings, pointReceipts, repCollectors, repRegistrars, timeEntries } from "@/db/schema";
import { recordRepPEvent } from "@/rep-p/audit.service";
import { createPrivateDownloadUrl, getPrivateObjectBytes, putPrivateObject } from "@/services/object-storage.service";
import { renderReceiptPdf } from "../pdf/point-receipt-pdf.service";
import { renderPointReceipt } from "../templates/point-receipt.renderer";
import { POINT_RECEIPT_FORMAT_VERSION, type PointReceiptData } from "../types";
import { DeferredPadesSignatureService, type PointReceiptSignatureService } from "./point-receipt-signature.service";
const MAX_RETRIES = 5;
function verificationSecret() { const value = process.env.RECEIPT_VERIFICATION_SECRET ?? process.env.BETTER_AUTH_SECRET; if (!value || value.length < 32) throw new Error("RECEIPT_VERIFICATION_SECRET deve possuir pelo menos 32 caracteres."); return value; }
function verificationToken(id: string) { return createHmac("sha256", verificationSecret()).update(`point-receipt:${id}`).digest("base64url"); }
function tokenHash(token: string) { return createHash("sha256").update(token).digest("hex"); }
function maskCpf(cpf: string) { return cpf.length === 11 ? `***.***.***-${cpf.slice(-2)}` : "Identificador protegido"; }
function formatCnpj(value: string) { return value.length === 14 ? `${value.slice(0, 2)}.${value.slice(2, 5)}.${value.slice(5, 8)}/${value.slice(8, 12)}-${value.slice(12)}` : value; }
function retryAt(count: number) { return new Date(Date.now() + [60_000, 300_000, 900_000, 3_600_000, 21_600_000][Math.min(count, 4)]); }
async function officialData(timeEntryId: string) { const [row] = await db.select({ entry: timeEntries, employeeName: employees.fullName, employeeRegistration: employees.registrationNumber, employeeCpf: employees.cpf, establishmentName: establishments.name, establishmentCnpj: establishments.cnpj, timezone: establishments.timezone, registrarIdentifier: repRegistrars.identifier }).from(timeEntries).innerJoin(employees, eq(employees.id, timeEntries.employeeId)).innerJoin(establishments, eq(establishments.id, timeEntries.establishmentId)).innerJoin(repRegistrars, eq(repRegistrars.id, timeEntries.registrarId)).innerJoin(repCollectors, eq(repCollectors.id, timeEntries.collectorId)).where(and(eq(timeEntries.id, timeEntryId), eq(timeEntries.source, "REP_P"))).limit(1); if (!row) return undefined; const nsr = row.entry.nsr; const establishmentId = row.entry.establishmentId; const registrarId = row.entry.registrarId; const collectorId = row.entry.collectorId; if (!nsr || !establishmentId || !registrarId || !collectorId) return undefined; const [legal] = await db.select().from(legalSettings).limit(1); return { ...row, entry: { ...row.entry, nsr, establishmentId, registrarId, collectorId }, employerName: legal?.employerName ?? row.establishmentName, employerDocument: legal?.employerId ?? row.establishmentCnpj }; }
export async function generatePointReceipt(timeEntryId: string, signature: PointReceiptSignatureService = new DeferredPadesSignatureService()) {
  const formatVersion = POINT_RECEIPT_FORMAT_VERSION; const [existing] = await db.select().from(pointReceipts).where(and(eq(pointReceipts.timeEntryId, timeEntryId), eq(pointReceipts.formatVersion, formatVersion))).limit(1); if (existing?.status === "AVAILABLE" || existing?.status === "SIGNED") return existing;
  const source = await officialData(timeEntryId); if (!source) return undefined; const id = existing?.id ?? crypto.randomUUID(); const token = verificationToken(id); const snapshot = { employeeName: source.employeeName, employeeRegistration: source.employeeRegistration, employeeDocumentMasked: maskCpf(source.employeeCpf), employerName: source.employerName, employerDocument: formatCnpj(source.employerDocument), establishmentName: source.establishmentName, registrarIdentifier: source.registrarIdentifier, timezone: source.timezone };
  let receipt = existing; if (!receipt) { const [created] = await db.insert(pointReceipts).values({ id, timeEntryId, employeeId: source.entry.employeeId, establishmentId: source.entry.establishmentId!, registrarId: source.entry.registrarId!, collectorId: source.entry.collectorId!, nsr: source.entry.nsr, recordedAt: source.entry.occurredAt, receiptNumber: `UP-${source.entry.nsr}-${id.slice(0, 8).toUpperCase()}`, status: "PENDING", formatVersion, snapshot, publicVerificationTokenHash: tokenHash(token) }).onConflictDoNothing({ target: [pointReceipts.timeEntryId, pointReceipts.formatVersion] }).returning(); receipt = created ?? (await db.select().from(pointReceipts).where(and(eq(pointReceipts.timeEntryId, timeEntryId), eq(pointReceipts.formatVersion, formatVersion))).limit(1))[0]; if (receipt) await recordRepPEvent(db, { eventType: "POINT_RECEIPT_CREATED", outcome: "SUCCESS", collectorId: source.entry.collectorId!, employeeId: source.entry.employeeId, nsr: source.entry.nsr, metadata: { receiptId: receipt.id, timeEntryId, formatVersion } }); }
  if (!receipt) throw new Error("Não foi possível reservar o comprovante.");
  try { const data: PointReceiptData = { receiptId: receipt.id, receiptNumber: receipt.receiptNumber, employeeName: snapshot.employeeName, employeeRegistration: snapshot.employeeRegistration, employeeDocumentMasked: snapshot.employeeDocumentMasked, employerName: snapshot.employerName, employerDocument: snapshot.employerDocument, establishmentName: snapshot.establishmentName, registrarIdentifier: snapshot.registrarIdentifier, recordedAt: receipt.recordedAt, timezone: snapshot.timezone, nsr: receipt.nsr, verificationToken: token }; const unsigned = renderReceiptPdf(renderPointReceipt(data)); await recordRepPEvent(db, { eventType: "POINT_RECEIPT_PDF_GENERATED", outcome: "SUCCESS", collectorId: receipt.collectorId, employeeId: receipt.employeeId, nsr: receipt.nsr, metadata: { receiptId: receipt.id, formatVersion } }); const signed = await signature.signPdf(unsigned); const hash = createHash("sha256").update(signed.bytes).digest("hex"); const year = new Intl.DateTimeFormat("en", { year: "numeric", timeZone: snapshot.timezone }).format(receipt.recordedAt); const month = new Intl.DateTimeFormat("en", { month: "2-digit", timeZone: snapshot.timezone }).format(receipt.recordedAt); const key = `point-receipts/${receipt.establishmentId}/${year}/${month}/${receipt.id}.pdf`; await putPrivateObject(key, signed.bytes, "application/pdf", { receiptId: receipt.id, sha256: hash, formatVersion }); const [available] = await db.update(pointReceipts).set({ status: "AVAILABLE", generatedAt: new Date(), signedAt: signed.signedAt, pdfFileKey: key, pdfHash: hash, signatureStatus: signed.status, signatureProvider: signed.provider, certificateIdentifier: signed.certificateIdentifier, certificateSubject: signed.certificateSubject, certificateValidFrom: signed.certificateValidFrom, certificateValidUntil: signed.certificateValidUntil, lastErrorCode: null, nextRetryAt: null }).where(eq(pointReceipts.id, receipt.id)).returning(); await recordRepPEvent(db, { eventType: "POINT_RECEIPT_AVAILABLE", outcome: "SUCCESS", collectorId: receipt.collectorId, employeeId: receipt.employeeId, nsr: receipt.nsr, metadata: { receiptId: receipt.id, timeEntryId, pdfHash: hash, signatureStatus: signed.status } }); return available; }
  catch { const count = receipt.retryCount + 1; const status = count >= MAX_RETRIES ? "REQUIRES_ATTENTION" : "FAILED"; const [failed] = await db.update(pointReceipts).set({ status, retryCount: count, lastErrorCode: "DOCUMENT_PIPELINE_UNAVAILABLE", nextRetryAt: count >= MAX_RETRIES ? null : retryAt(count) }).where(eq(pointReceipts.id, receipt.id)).returning(); await recordRepPEvent(db, { eventType: "POINT_RECEIPT_GENERATION_FAILED", outcome: "REJECTED", collectorId: receipt.collectorId, employeeId: receipt.employeeId, nsr: receipt.nsr, reasonCode: "DOCUMENT_PIPELINE_UNAVAILABLE", metadata: { receiptId: receipt.id, timeEntryId, retryCount: count } }); return failed; }
}
export async function recoverPointReceipts(limit = 50) { const now = new Date(); const rows = await db.select({ timeEntryId: pointReceipts.timeEntryId }).from(pointReceipts).where(and(inArray(pointReceipts.status, ["PENDING", "FAILED"]), or(isNull(pointReceipts.nextRetryAt), lte(pointReceipts.nextRetryAt, now)))).orderBy(asc(pointReceipts.createdAt)).limit(limit); const results = []; for (const row of rows) results.push(await generatePointReceipt(row.timeEntryId)); return results; }
export async function listEmployeePointReceipts(employeeId: string) { return db.select().from(pointReceipts).where(eq(pointReceipts.employeeId, employeeId)).orderBy(desc(pointReceipts.recordedAt)); }
export async function listAdminPointReceipts() { return db.select({ receipt: pointReceipts, employeeName: employees.fullName, establishmentName: establishments.name }).from(pointReceipts).innerJoin(employees, eq(employees.id, pointReceipts.employeeId)).innerJoin(establishments, eq(establishments.id, pointReceipts.establishmentId)).orderBy(desc(pointReceipts.recordedAt)); }
export async function getPointReceiptForAccess(id: string, employeeId?: string) { const [receipt] = await db.select().from(pointReceipts).where(and(eq(pointReceipts.id, id), employeeId ? eq(pointReceipts.employeeId, employeeId) : undefined)).limit(1); return receipt; }
export async function receiptVerificationPath(id: string, employeeId?: string) { const receipt = await getPointReceiptForAccess(id, employeeId); return receipt ? `/verificar/comprovante/${verificationToken(receipt.id)}` : undefined; }
export async function privateReceiptDownload(id: string, employeeId?: string) { const receipt = await getPointReceiptForAccess(id, employeeId); if (!receipt?.pdfFileKey || !receipt.pdfHash) return undefined; const bytes = await getPrivateObjectBytes(receipt.pdfFileKey); const actual = createHash("sha256").update(bytes).digest("hex"); if (actual !== receipt.pdfHash) { await recordRepPEvent(db, { eventType: "POINT_RECEIPT_INTEGRITY_MISMATCH", outcome: "REJECTED", collectorId: receipt.collectorId, employeeId: receipt.employeeId, nsr: receipt.nsr, metadata: { receiptId: receipt.id, expectedHash: receipt.pdfHash, actualHash: actual } }); throw new Error("INTEGRITY_MISMATCH"); } return createPrivateDownloadUrl(receipt.pdfFileKey, `comprovante-${receipt.nsr}.pdf`); }
export async function verifyPublicReceipt(token: string) { const [receipt] = await db.select({ status: pointReceipts.status, nsr: pointReceipts.nsr, recordedAt: pointReceipts.recordedAt, snapshot: pointReceipts.snapshot, formatVersion: pointReceipts.formatVersion, pdfHash: pointReceipts.pdfHash }).from(pointReceipts).where(eq(pointReceipts.publicVerificationTokenHash, tokenHash(token))).limit(1); return receipt?.status === "AVAILABLE" ? receipt : undefined; }
