import "server-only";
import { createHash } from "node:crypto";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { aejGenerations } from "@/db/schema";
import { getPrivateObjectBytes, createPrivateDownloadUrl } from "@/services/object-storage.service";
import { recordAudit } from "@/services/audit.service";
import { validateAejBytes } from "@/modules/official-documents/validators/aej.validator";
import { DigitalSignatureService } from "./digital-signature.service";

const hash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
export async function signAejGeneration(id: string, performedBy: string, signatures = new DigitalSignatureService()) { const [generation] = await db.select().from(aejGenerations).where(eq(aejGenerations.id, id)).limit(1); if (!generation || !["GENERATED", "SIGNED"].includes(generation.status)) throw new Error("AEJ_NOT_READY_FOR_SIGNATURE"); const document = await getPrivateObjectBytes(generation.fileKey); if (hash(document) !== generation.fileHash || validateAejBytes(document).some((issue) => issue.severity === "ERROR")) throw new Error("AEJ_INTEGRITY_MISMATCH"); await recordAudit(db, { action: "AEJ_SIGNATURE_STARTED", entity: "AEJ_GENERATION", entityId: id, performedBy, after: { inputHash: generation.fileHash } }); try { const result = await signatures.signCades("AEJ", id, document, `${generation.fileKey}.p7s`); await db.update(aejGenerations).set({ status: "SIGNED", signatureStatus: "SIGNED", signatureFileKey: result.operation.signatureFileKey, signatureHash: result.outputHash, signedAt: result.operation.completedAt ?? new Date() }).where(eq(aejGenerations.id, id)); await recordAudit(db, { action: "AEJ_SIGNED", entity: "AEJ_GENERATION", entityId: id, performedBy, after: { inputHash: generation.fileHash, signatureHash: result.outputHash, certificateSerialNumber: result.certificate.serialNumber } }); return result; } catch (error) { await db.update(aejGenerations).set({ signatureStatus: "FAILED" }).where(eq(aejGenerations.id, id)); throw error; } }
export async function downloadAejSignature(id: string, performedBy: string) { const [generation] = await db.select().from(aejGenerations).where(eq(aejGenerations.id, id)).limit(1); if (!generation?.signatureFileKey || !generation.signatureHash || generation.signatureStatus !== "SIGNED") return undefined; const signature = await getPrivateObjectBytes(generation.signatureFileKey); if (hash(signature) !== generation.signatureHash) throw new Error("SIGNATURE_HASH_MISMATCH"); await recordAudit(db, { action: "AEJ_SIGNATURE_DOWNLOADED", entity: "AEJ_GENERATION", entityId: id, performedBy, after: { signatureHash: generation.signatureHash } }); return createPrivateDownloadUrl(generation.signatureFileKey, `${generation.fileName}.p7s`); }
